###### SAH perforation model Systematic Review and Meta-analysis ###########


# Setting working directory:
setwd("/users/tsand/desktop/SAH project Meta-analysis data/")

# Loading libraries used for further calculations:
library(dplyr)
library(plyr)
library(readr)
library(tidyverse)
library(scales)
library(metafor)
library(clubSandwich)
library(orchaRd)



# Loading reconciled study annotations:
SA <- read.csv("SAH study annotations reconciliation.csv")

# Filter only the reconciled annotations:
SA <- SA %>% filter(AnnotatorIdStr == "TIMO")


# Loading reconciled outcome annotations:
OA <- read.csv("SAH outcome reconciliation.csv")

# Filter only the reconciled annotations:
OA <- OA %>% filter(AnnotatorIdStr == "TIMO")



## Number of included articles:

SA %>% select(3) %>% unique() %>% nrow()

OA %>% select(1) %>% unique() %>% nrow()

# Are there articles that are an element of OA but not SA:
OA %>% filter(!is.element(StudyIdStr,SA$StudyIdStr)) %>% select(1)

# Removing articles that have no outcome annotations (which means they got excluded) from study annotations:
SA <- SA %>% filter(is.element(StudyIdStr,OA$StudyIdStr))



## Removing column from SA and OA that are irrelevant:

# Loading the manually created list of irrelevant columns of the file that was generated by SyRF:
Irrelevant_columns <- read.csv("List of columns to remove from SAH annotations.csv")

# Removing NA values:
Irrelevant_columns_study <- Irrelevant_columns %>% filter(Study != "NA") %>% select(1) %>% toString()
Irrelevant_columns_outcomes <- Irrelevant_columns %>% filter(Outcomes != "NA") %>% select(2) %>% toString()

# Removing irrelevant columns from SA:
SA <- SA[,-c(1, 2, 6, 7, 9, 10, 12, 15, 18, 19, 21, 22, 24, 27, 30, 31, 33, 34, 36, 39, 42, 45, 46, 48, 51, 54, 57, 60, 63, 64, 66, 69, 70, 72, 73, 75, 76, 78, 79, 81, 82, 84, 85, 87, 88, 90, 93, 94, 96, 99, 100, 102, 103, 105, 108, 109, 111, 112, 114, 115, 117, 118)]

# Removing irrelevant columns from OA:
OA <- OA[,-c(3, 4, 5, 6, 7, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 68, 69, 70, 71, 72, 74, 75, 76, 77, 78, 79, 80, 81,seq(90,1024,1))]



### Analysing study annotations:

# Table of parameter phenotypes:
table(SA$X041138a4.9468.45b1.8eea.7bd17ca09840_Was.the.size.of.the.filament.used.for.perforation.model.reported.)
table(SA$X0bd6c847.545f.466f.bb0e.16bdfbbb4369_Was.the.perforation.entry.point.reported.)
table(SA$X1576fbb4.2a1a.4ed0.ba1e.9760ae3e8cff_Were.the.mice.intubated.)
table(SA$X18379abd.003c.4af8.8186.91b5c45b2c65_Which.mouse.strain.was.used.)
table(SA$X1b642852.1651.4649.8659.ceb696562040_What.are.the.information.on.mice.sex.)
table(SA$X1c85e257.be79.41dd.8fc1.15f288825871_Was.the.location.of.perforation.reported.)
table(SA$X29507fcf.6301.423d.8d54.ea3e700a2e46_Were.any.methods.to.reduce.postsurgical.pain.stress.of.mice.reported)
table(SA$X35ac3c0e.ce1b.46b7.b6c1.13f58f6bd78a_Was.intracranial.pressure.montitored.)
table(SA$X4ee728ab.4cb9.444e.96ae.c2e96b1864a9_What.was.the.size.of.the.filament.used.for.perforation.model.)
table(SA$X552b6157.e446.49ad.90c1.09ee1c4f929d_How.were.the.mice.anaesthetised.)
table(SA$X63c6d74f.9c40.4ee4.b929.110a1b46dba8_How.were.the.animal.housing.conditions.described.)
table(SA$X740b1a07.0128.4e83.b958.a721e289f57a_Were.animals.with.immunodepression.used.for.experiments.)

table(SA$X75220509.5fa4.4765.94f0.b1b618b8da28_Which.intravenous.anaesthetic.was.used.) %>% as.data.frame() %>% write.csv("injective_anaesthetics1.csv", row.names = F)

table(SA$X78b2e595.fe44.4727.9a0c.664e936af6e1_How.were.the.other.animal.housing.conditions.described.) %>% as.data.frame() %>% write.csv("other_housing_conditions1.csv", row.names = F)

table(SA$X799fbc30.2d1d.4713.a549.9f0a56bdd329_Which.filament.was.used.for.perforation.model.)
table(SA$X9d26e1f7.7cc8.4cd8.be95.ab5576e4cb13_Which.other.filament.type.was.used.for.perforation.model.) %>% as.data.frame() %>% write.csv("filament_types1.csv", row.names = F)

table(SA$X7cf59b31.bba7.4207.8ff5.750bec9bfd9c_Where.was.the.location.of.perforation.) %>% as.data.frame() %>% write.csv("perforation_location1.csv", row.names = F)

table(SA$X847f84e6.8338.45b9.81f0.7a578f6ff564_What.is.the.age.of.the.mice.) %>% as.data.frame() %>% write.csv("mice_age1.csv", row.names = F)

table(SA$X8c711833.0304.4bf5.841c.821fa677f4d6_Is.the.age.of.the.mice.reported.)

table(SA$X90048d0f.3575.4024.9cc6.72d98225efbf_Which.other.anaesthetical.procedure.was.used.)

table(SA$X94ba69b7.d5c7.4a3a.b47a.db502d436b44_Which.intervention.was.tested.) %>% as.data.frame() %>% write.csv("interventions1.csv", row.names = F)

table(SA$a519b196.b50e.4e4d.bfa9.5e01e6157ad8_How.was.the.weight.of.the.mice.)  %>% as.data.frame() %>% write.csv("mice_weight1.csv", row.names = F)

table(SA$fa4eee38.02d9.40f4.aebd.93cb546881cd_Were.information.about.the.weight.of.the.mice.given.)
table(SA$X1b642852.1651.4649.8659.ceb696562040_What.are.the.information.on.mice.sex.)

table(SA$acd50172.1d29.4bf1.a5ec.e5320c86e83f_Which.inhalative.anaesthetic.was.used.) %>% as.data.frame() %>% write.csv("inhalative_anaesthetic1.csv", row.names = F)

table(SA$b56d53d2.9833.4916.8493.24526add7cd0_Was.the.duration.of.surgical.treatment.of.perforation.reported.)
table(SA$c76b9578.c4de.47cf.adad.1829bf125b1e_Which.methods.to.reduce.postsurgical.pain.stress.of.mice.were.used.) %>% as.data.frame() %>% write.csv("postsurgical_treatment1.csv", row.names = F)

table(SA$ec5e59fb.753d.4d95.a11e.1c15ff803d14_Mouse.strain.reported.)
table(SA$efea8113.a97b.4bb6.8940.2205a6b5b482_How.long.was.the.duration.of.surgical.treatment.of.perforation.)
table(SA$fa4eee38.02d9.40f4.aebd.93cb546881cd_Were.information.about.the.weight.of.the.mice.given.)

table(SA$feef2370.3b71.4e0c.9724.8c0c3eba7970_Where.was.the.perforation.entry.point.) %>% as.data.frame() %>% write.csv("perforation_entry1.csv", row.names = F)



### Analysing outcome annotations:

# Number of total experiments:
OA %>% distinct(StudyIdStr, Experiment) %>% unique() %>% nrow()

# How many studies have reported the outcomes?
OA %>% filter(Which.type.of.outcome.was.assessed. == "Mortality rate (%)") %>% select(StudyIdStr) %>% unique() %>% nrow()
OA %>% filter(Which.type.of.outcome.was.assessed. == "SAH grade") %>% select(StudyIdStr) %>% unique() %>% nrow()
# vessel diameter:
OA %>% filter(Which.type.of.outcome.was.assessed. != "Mortality rate (%)", Which.type.of.outcome.was.assessed. != "SAH grade") %>% select(StudyIdStr) %>% unique() %>% nrow()

# How many experiments have reported the outcomes?
OA %>% filter(Which.type.of.outcome.was.assessed. == "Mortality rate (%)") %>% distinct(StudyIdStr, Experiment) %>% unique() %>% nrow()
OA %>% filter(Which.type.of.outcome.was.assessed. == "SAH grade") %>% distinct(StudyIdStr, Experiment) %>% unique() %>% nrow()
# vessel diameter:
OA %>% filter(Which.type.of.outcome.was.assessed. != "Mortality rate (%)", Which.type.of.outcome.was.assessed. != "SAH grade") %>% distinct(StudyIdStr, Experiment) %>% unique() %>% nrow()


# Vehicle controls
# Number of articles with vehicle controls
OA %>% filter(Vehicle.control. != "") %>% select(1) %>% unique() %>% nrow()
# Number of experiments with vehicle controls
OA %>% filter(Vehicle.control. != "") %>% distinct(StudyIdStr, Experiment) %>% unique() %>% nrow()


# SAH grading systems
# Number of articles with the SAH grading systems
OA %>% filter(Reconciled.SAH.grading.system != "") %>% distinct(StudyIdStr, .keep_all = TRUE) %>% select(18) %>% table()
# Number of experiments with the SAH grading systems
OA %>% filter(Reconciled.SAH.grading.system != "") %>% distinct(StudyIdStr, Experiment, .keep_all = TRUE) %>% select(18) %>% table()


# Vessel diameter measurement:

# Method
OA %>% filter(Reconciled.diameter.measurement.method != "") %>% distinct(StudyIdStr, .keep_all = TRUE) %>% select(19) %>% table()
OA %>% filter(Reconciled.diameter.measurement.method != "") %>% distinct(StudyIdStr, Experiment, .keep_all = TRUE) %>% select(19) %>% table()
# Vessel
OA %>% filter(Reconciled.Vessel.for.diameter.assessment != "") %>% distinct(StudyIdStr, .keep_all = TRUE) %>% select(20) %>% table()
OA %>% filter(Reconciled.Vessel.for.diameter.assessment != "") %>% distinct(StudyIdStr, Experiment, .keep_all = TRUE) %>% select(20) %>% table()


## Mortality assessment times:
# all data points:
OA %>% filter(Which.type.of.outcome.was.assessed. == "Mortality rate (%)") %>% select(Time) %>% table() %>% as.data.frame() %>% write.csv(file = "Mortality_times1.csv", row.names = F)
# SAH data points:
OA %>% filter(Which.type.of.outcome.was.assessed. == "Mortality rate (%)", ModelLabel == "SAH") %>% select(Time) %>% table() %>% as.data.frame() %>% write.csv(file = "Mortality_times_SAH1.csv", row.names = F)
# SHAM data points:
OA %>% filter(Which.type.of.outcome.was.assessed. == "Mortality rate (%)", ModelLabel == "SHAM") %>% select(Time) %>% table() %>% as.data.frame() %>% write.csv(file = "Mortality_times_SHAM1.csv", row.names = F)

# Number of articles with the particular timepoints:
OA %>% filter(Which.type.of.outcome.was.assessed. == "Mortality rate (%)") %>% distinct(StudyIdStr, Time) %>% select(Time) %>% table() %>% as.data.frame() %>% arrange(desc(Freq))
# Number of experiments with the particular timepoints:
OA %>% filter(Which.type.of.outcome.was.assessed. == "Mortality rate (%)") %>% distinct(StudyIdStr, Experiment, Time) %>% select(Time) %>% table() %>% as.data.frame() %>% arrange(desc(Freq))

# Number of articles with the particular timepoints in SAH groups:
OA %>% filter(Which.type.of.outcome.was.assessed. == "Mortality rate (%)", ModelLabel == "SAH") %>% distinct(StudyIdStr, Time) %>% select(Time) %>% table() %>% as.data.frame() %>% arrange(desc(Freq))
# Number of experiments with the particular timepoints in SAH groups:
OA %>% filter(Which.type.of.outcome.was.assessed. == "Mortality rate (%)", ModelLabel == "SAH") %>% distinct(StudyIdStr, Experiment, Time) %>% select(Time) %>% table() %>% as.data.frame() %>% arrange(desc(Freq))

# Number of articles with the particular timepoints in SHAM groups:
OA %>% filter(Which.type.of.outcome.was.assessed. == "Mortality rate (%)", ModelLabel == "SHAM") %>% distinct(StudyIdStr, Time) %>% select(Time) %>% table() %>% as.data.frame() %>% arrange(desc(Freq))
# Number of experiments with the particular timepoints in SHAM groups:
OA %>% filter(Which.type.of.outcome.was.assessed. == "Mortality rate (%)", ModelLabel == "SHAM") %>% distinct(StudyIdStr, Experiment, Time) %>% select(Time) %>% table() %>% as.data.frame() %>% arrange(desc(Freq))


## Number of animals:

# Overall total number of animals
Number_Animals <- OA %>% distinct(StudyIdStr, Experiment, NumberOfAnimals)
Number_Animals$NumberOfAnimals <- as.numeric(Number_Animals$NumberOfAnimals)
# NA means "not reported"
Number_Animals_Dup <- Number_Animals %>% select(StudyIdStr,Experiment) %>% count()
Number_Animals_Dup$joined_StudyID_Exp <- paste(Number_Animals_Dup$StudyIdStr, Number_Animals_Dup$Experiment)
Number_Animals$joined_StudyID_Exp <- paste(Number_Animals$StudyIdStr, Number_Animals$Experiment)
# Filtering the data point with the highest number of animals per experiment:
List1a <- list()
for (a in 1:nrow(Number_Animals_Dup)) {
  dummya <- print(max(Number_Animals[Number_Animals$joined_StudyID_Exp == Number_Animals_Dup[a,4],2]))
  List1a[[length(List1a)+1]] = dummy
}
List1a <- List1a %>% as.data.frame()
rowSums(List1a, na.rm = T)


## Not reported number of animals:

# Converting into numerical values
OA$NumberOfAnimals <- OA$NumberOfAnimals %>% as.numeric()
# NA values mean not reported
OA %>% filter(is.na(NumberOfAnimals) == TRUE) %>% select(1,6,8)
              



### Creating the dataframe for meta-analysis:

# Taking OA as the basis
MA <- OA



## Adding the study annotations to MA

write.csv(SA, file = "SA1.csv", row.names = F)
SA <- read.csv("SA.csv")

# Intubation
for (m in 1:nrow(MA)) {
  MA[m,22] <- SA[SA$StudyIdStr == MA[m,1],5]
}
colnames(MA)[22] <- paste("intubation")

# Mouse strain
for (m in 1:nrow(MA)) {
  MA[m,23] <- SA[SA$StudyIdStr == MA[m,1],57]
}
colnames(MA)[23] <- paste("strain")

# Postsurgical treatment
SA[SA$StudyIdStr == "4c4e2785-7a37-4372-a212-00a99a93b34a",11] <- "Reported that no postsurgical treatment was given"
for (m in 1:nrow(MA)) {
  MA[m,24] <- SA[SA$StudyIdStr == MA[m,1],11]
}
colnames(MA)[24] <- paste("postsurgical treatment")

# ICP monitoring
for (m in 1:nrow(MA)) {
  MA[m,25] <- SA[SA$StudyIdStr == MA[m,1],13]
}
colnames(MA)[25] <- paste("ICP monitoring")

# Filament size
SA[SA$X4ee728ab.4cb9.444e.96ae.c2e96b1864a9_What.was.the.size.of.the.filament.used.for.perforation.model. == 0,16] <- "not reported"
SA[SA$X4ee728ab.4cb9.444e.96ae.c2e96b1864a9_What.was.the.size.of.the.filament.used.for.perforation.model. == "5-0 monofilament",16] <- "5-0"
for (m in 1:nrow(MA)) {
  MA[m,26] <- SA[SA$StudyIdStr == MA[m,1],16]
}
colnames(MA)[26] <- paste("filament size")

# Anesthesia
SA[SA$X552b6157.e446.49ad.90c1.09ee1c4f929d_How.were.the.mice.anaesthetised. == "Other",17] <- "Injective and inhalative anaesthesia combined"
for (m in 1:nrow(MA)) {
  MA[m,27] <- SA[SA$StudyIdStr == MA[m,1],17]
}
colnames(MA)[27] <- paste("type of anesthesia")

# Single or group cage
SA[SA$X63c6d74f.9c40.4ee4.b929.110a1b46dba8_How.were.the.animal.housing.conditions.described. == "group",58] <- "group cage"
SA[SA$X63c6d74f.9c40.4ee4.b929.110a1b46dba8_How.were.the.animal.housing.conditions.described. == "single cage",58] <- "single cage"
SA[is.na(SA$V58),58] <- "not reported whether single or group cage"
colnames(SA)[58] <- paste("Singe/Group cage")
for (m in 1:nrow(MA)) {
  MA[m,28] <- SA[SA$StudyIdStr == MA[m,1],58]
}
colnames(MA)[28] <- paste("Singe/Group cage")
write.csv(SA$X78b2e595.fe44.4727.9a0c.664e936af6e1_How.were.the.other.animal.housing.conditions.described., file = "other_housing_conditions_match1.csv")
SA %>% select(1,22,28) %>% write.csv(file = "other_housing_conditions_match1.csv", row.names = F)

# Other housing conditions parameters
# loading reconciled other housing conditions parameters:
other_housing_cond_parameters <- read.csv("Mice_housing_conditions_parameters.csv")
# adding them to MA
for (m in 1:nrow(MA)) {
  MA[m,seq(29,34)] <- other_housing_cond_parameters[other_housing_cond_parameters == MA[m,1],seq(3,8,1)]
}
colnames(MA)[seq(29,34)] <- paste(c("12-hour light-dark cycle",	"free access to food and water", "controlled humidity",	"controlled temperature",	"temperature (°C)",	"humidity (%)"))

# Injective Anesthetics
write.csv(SA[,c(1,26)], file = "injective_anesthetics_overview1.csv", row.names = F)
Injective_anesthetics_reconciled_overview <- read.csv("Injective_anesthetics_reconciled_overview.csv")
MA %>% filter(!is.element(StudyIdStr, Injective_anesthetics_reconciled_overview$StudyID)) %>% select(1) %>% unique() %>% write.csv("missing_injective_anesthetics.csv", row.names = F)
# adding them to MA
for (m in 1:nrow(MA)) {
  MA[m,seq(35,36)] <- Injective_anesthetics_reconciled_overview[Injective_anesthetics_reconciled_overview == MA[m,1],seq(3,4,1)]
}
colnames(MA)[seq(35,36,1)] <- paste(c("injetive_anesthetic_substance",	"injetive_anesthetic_dose"))

# Inhalative Anesthetics
write.csv(SA[,c(1,44)], file = "inhalative_anesthetics_overview.csv", row.names = F)
SA %>% filter(SA$X552b6157.e446.49ad.90c1.09ee1c4f929d_How.were.the.mice.anaesthetised. != "Inhalative") %>% select(1) 
Inhalative_anesthetics_reconciled_overview <- read.csv("Inhalative_anesthetics_reconciled_overview.csv")
# adding them to MA
for (m in 1:nrow(MA)) {
  MA[m,seq(37,41,1)] <- Inhalative_anesthetics_reconciled_overview[Inhalative_anesthetics_reconciled_overview$X == MA[m,1],seq(2,6,1)]
}
colnames(MA)[seq(37,41,1)] <- paste(c("Inhalative anesthesiea Substance",	"Isoflurane Induction",	"Isoflurane Maintenance", "Inhalative Anesthesia O2/N2-Mixture",	"Inhalative Anesthesia Flow"))

# Filament type
write.csv(SA[,c(1,40)], file = "filament_types_overview.csv", row.names = F)
filament_types_reconciled_overview <- read.csv("filament_types_reconciled_overview.csv")
# adding them to MA
for (m in 1:nrow(MA)) {
  MA[m,seq(42,48,1)] <- filament_types_reconciled_overview[filament_types_reconciled_overview$StudyID == MA[m,1],seq(4,10,1)]
}
colnames(MA)[seq(42,48,1)] <- paste(c("material","lenght", "diameter",	"sharpened tip", "blunted tip", "monofilament",	"suture"))

# Location of perforation
write.csv(SA[,c(1,34)], file = "perforation_location_overview1.csv", row.names = F)
perforation_location_reconciled_overview <- read.csv("perforation_location_reconciled_overview.csv")
# adding them to MA
for (m in 1:nrow(MA)) {
  MA[m,seq(49,50,1)] <- perforation_location_reconciled_overview[perforation_location_reconciled_overview$StudyID == MA[m,1],seq(4,5,1)]
}
colnames(MA)[seq(49,50,1)] <- paste(c("location_perforation","side_location_perforation"))

# Mice age
write.csv(SA[,c(1,35)], file = "mice_age_overview1.csv", row.names = F)
mice_age_reconciled_overview <- read.csv("mice_age_reconciled_overview.csv")
# adding them to MA
for (m in 1:nrow(MA)) {
  MA[m,seq(51,52,1)] <- mice_age_reconciled_overview[mice_age_reconciled_overview$StudyID == MA[m,1],seq(4,5,1)]
}
colnames(MA)[seq(51,52,1)] <- paste(c("age_median","age_plus_minus"))

# Mice weight
write.csv(SA[,c(1,41)], file = "mice_weight_overview1.csv", row.names = F)
mice_weight_reconciled_overview <- read.csv("mice_weight_reconciled_overview.csv")
# adding them to MA
for (m in 1:nrow(MA)) {
  MA[m,seq(53,54,1)] <- mice_weight_reconciled_overview[mice_weight_reconciled_overview$StudyID == MA[m,1],seq(4,5,1)]
}
colnames(MA)[seq(53,54,1)] <- paste(c("weight_median","weight_plus_minus"))

# Duration of SAH perforation surgery
# as there are only two articles with reported surgery duration they get manually added:
MA[MA$StudyIdStr == "11660f81-c343-4396-a097-74ca3430d6fa", 55] <- 30
MA[MA$StudyIdStr == "6e8bdf4f-1be9-475c-8883-4bbbb6310b66", 55] <- 15
colnames(MA)[55] <- paste("surgery_duration")

# Detailed postsurgical treatment
write.csv(SA[,c(1,49)], file = "detailed_postsurgical_treatment_overview1.csv", row.names = F)
postsurgical_treatment_reconciled_overview <- read.csv("postsurgical_treatment_reconciled_overview.csv")
# adding them to MA
for (m in 1:nrow(MA)) {
  MA[m,56] <- postsurgical_treatment_reconciled_overview[postsurgical_treatment_reconciled_overview$StudyID == MA[m,1],5]
}
colnames(MA)[(56)] <- paste("subtance_postsurgical_treatment")

# Perforation entry point
write.csv(SA[,c(1,56)], file = "entry_perforation1.csv", row.names = F)
perforation_entry_reconciled_overview <- read.csv("perforation_entry_reconciled_overview.csv")
# adding them to MA
for (m in 1:nrow(MA)) {
  MA[m,seq(57,58,1)] <- perforation_entry_reconciled_overview[perforation_entry_reconciled_overview$StudyID == MA[m,1],seq(4,5,1)]
}
colnames(MA)[seq(57,58,1)] <- paste(c("vessel_entry_perforation","side_entry_perforation"))




### Dividing the data for meta-analysis into the particular outcomes:

# Converting outcome data into numerical values:
MA$Average <- as.numeric(MA$Average)
MA$Time <- as.numeric(MA$Time)
MA$NumberOfAnimals <- as.numeric(MA$NumberOfAnimals)

# Mortality:
MMA <- MA %>% filter(Which.type.of.outcome.was.assessed. == "Mortality rate (%)")

# SAH grade:
GMA <- MA %>% filter(Which.type.of.outcome.was.assessed. == "SAH grade")

# Vessel diameter:
VMA <- MA %>% filter(Which.type.of.outcome.was.assessed. != "Mortality rate (%)", Which.type.of.outcome.was.assessed. != "SAH grade")

# checking if the divison was successful:
nrow(MMA) + nrow(GMA) + nrow(VMA) == nrow(MA)
# if its TRUE we can continue




##### Meta-analysis


#### Mortality

# adding a column with the back-calculated number of deaths:
MMA$deaths <- round(MMA$Average * MMA$NumberOfAnimals / 100, 0)


### SAH group:
MMAP <- MMA %>% filter(ModelLabel == "SAH")

# different timepoints:
MMAP1 <- MMAP %>% filter(Time == 1)
MMAP2 <- MMAP %>% filter(Time == 2)
MMAP3 <- MMAP %>% filter(Time == 3)
MMAP7 <- MMAP %>% filter(Time == 7)


### Model: Binomial-normal model for the meta-analysis of proportions

## Including all timepoints:
resMMAP <- rma(measure="PLO", xi=deaths, ni=NumberOfAnimals, method = "REML", data=MMAP)
resMMAP
predict(resMMAP, transf=transf.ilogit, digits=3)
# CAVE: Biased due to multiple data from the same study/experiment

# Moderator: Time
resMMAPTime <- rma(measure="PLO", xi=deaths, ni=NumberOfAnimals, mods = ~ Time, method = "REML", data=MMAP)
resMMAPTime

# Moderator: Location of perforation:
resMMAPLocation <- rma(measure="PLO", xi=deaths, ni=NumberOfAnimals, mods = ~ factor(location_perforation), method = "REML", data=MMAP)
resMMAPLocation

# Moderator: Type of anesthesia
resMMAPAnes <- rma(measure="PLO", xi=deaths, ni=NumberOfAnimals, mods = ~ factor(MMAP$`type of anesthesia`), method = "REML", data=MMAP)
resMMAPAnes



## Including only t=1
resMMAP1 <- rma(measure="PLO", xi=deaths, ni=NumberOfAnimals, method = "REML", data=MMAP1)
resMMAP1
predict(resMMAP1, transf=transf.ilogit, digits=3)

# Moderator: Location of perforation:
resMMAP1Location <- rma(measure="PLO", xi=deaths, ni=NumberOfAnimals, mods = ~ factor(location_perforation), method = "REML", data=MMAP1)
resMMAP1Location

# Moderator: Type of anesthesia
resMMAP1Anes <- rma(measure="PLO", xi=deaths, ni=NumberOfAnimals, mods = ~ factor(MMAP1$`type of anesthesia`), method = "REML", data=MMAP1)
resMMAP1Anes







### Calculating effect sizes with metafor (according to PDF guide):
MMAPes <- escalc(xi = deaths, ni = NumberOfAnimals, measure = "PLO", data = MMAP)
MMAPes.logit <- rma(yi, vi, method = "DL", level = 95, data = MMAPes)
MMAPes.logit.predict <- predict(MMAPes.logit, transf=transf.ilogit)
print(MMAPes.logit)
print(MMAPes.logit.predict, digits = 6)
confint(MMAPes.logit)

# Exploring heterogeneity: Subgroup analysis (Type of anesthesia: injevtive vs inhalative):
# Assumption: no common between-study variance component (no pooled tau2):
MMAPesSG1Anes <- rma(yi, vi, method = "DL", level = 95, subset=MMAPes$type.of.anesthesia=="Injective", data = MMAPes)
MMAPesSG2Anes <- rma(yi, vi, method = "DL", level = 95, subset=MMAPes$type.of.anesthesia=="Inhalative", data = MMAPes)
MMAPesSG1Anes.predict=predict(MMAPesSG1Anes, transf=transf.ilogit)
MMAPesSG2Anes.predict=predict(MMAPesSG2Anes, transf=transf.ilogit)
dat.diffvar=data.frame(estimate=c(MMAPesSG1Anes$b, MMAPesSG2Anes$b),
                       stderror=c(MMAPesSG1Anes$se, MMAPesSG2Anes$se),
                       moderator=c("Injective", "Inhalative"),
                       tau2=round(c(MMAPesSG1Anes$tau2,
                                    MMAPesSG2Anes$tau2), 3))
subganal.moderator=rma(estimate, sei=stderror, mods=~moderator,
                       method="FE", data=dat.diffvar)
pes.logit.moderator_SGAnes=rma(estimate, sei=stderror, method="FE", data=dat.diffvar)
pes.moderator_SGAnes=predict(pes.logit.moderator_SGAnes, transf=transf.ilogit)
print(MMAPesSG1Anes); print(MMAPesSG1Anes.predict)
print(MMAPesSG2Anes); print(MMAPesSG2Anes.predict)
print(subganal.moderator)
print(pes.moderator_SGAnes)

# Meta-regression (according to PDF guide):
# Time
MMAPesRegTime <- rma(yi, vi, method = "DL", level = 95, mods = ~Time, data = MMAPes)
print(MMAPesRegTime)
predict(MMAPesRegTime,transf=transf.ilogit)
# Type of anesthesia
MMAPesRegAnes <- rma(yi, vi, method = "DL", level = 95, mods = ~factor(MMAPes$type.of.anesthesia), data = MMAPes)
print(MMAPesRegAnes)
predict(MMAPesRegAnes,transf=transf.ilogit)
# Multivariable Meta-regression: Time and Type of anesthesia
MMAPesRegTimeAnes <- rma(yi, vi, method = "DL", level = 95, mods = ~cbind(factor(MMAPes$type.of.anesthesia), Time), data = MMAPes)
print(MMAPesRegTimeAnes)





### Solve the problem of multiple data from an article leading to bias due to lack of independence of data (for the SAH group):

## only without vehicle control:
MMAPVN <- MMAP %>% filter(Vehicle.control. == "")
# Getting on row per study and experiment:
MMAPVN$joinedSE <- paste(MMAPVN$StudyIdStr,MMAPVN$Experiment)
SEdistinctVN <- as.data.frame(unique(MMAPVN$joinedSE)) 
for (seVN in 1:nrow(SEdistinctVN)) {
  SEdistinctVN[seVN,2] <- MMAPVN %>% filter(joinedSE == SEdistinctVN[seVN,1]) %>% select(deaths) %>% max()
}
for (seVN in 1:nrow(SEdistinctVN)) {
  SEdistinctVN[seVN,3] <- MMAPVN %>% filter(joinedSE == SEdistinctVN[seVN,1]) %>% select(NumberOfAnimals) %>% max()
}
for (seVN in 1:nrow(SEdistinctVN)) {
  SEdistinctVN[seVN,4] <- MMAPVN %>% filter(joinedSE == SEdistinctVN[seVN,1]) %>% select(Time) %>% max()
}
colnames(SEdistinctVN)[c(2,3,4)] <- paste(c("deaths", "number of animals", "longest time"))


## only with vehicle control:
MMAPVP <- MMAP %>% filter(Vehicle.control. != "")
nrow(MMAPVN)+nrow(MMAPVP)==nrow(MMAP)
# if its TRUE we can continue
# Getting on row per study and experiment:
MMAPVP$joinedSE <- paste(MMAPVP$StudyIdStr,MMAPVP$Experiment)
SEdistinctVP <- as.data.frame(unique(MMAPVP$joinedSE)) 
for (seVP in 1:nrow(SEdistinctVP)) {
  SEdistinctVP[seVP,2] <- MMAPVP %>% filter(joinedSE == SEdistinctVP[seVP,1]) %>% select(deaths) %>% max()
}
for (seVP in 1:nrow(SEdistinctVP)) {
  SEdistinctVP[seVP,3] <- MMAPVP %>% filter(joinedSE == SEdistinctVP[seVP,1]) %>% select(NumberOfAnimals) %>% max()
}
for (seVP in 1:nrow(SEdistinctVP)) {
  SEdistinctVP[seVP,4] <- MMAPVP %>% filter(joinedSE == SEdistinctVP[seVP,1]) %>% select(Time) %>% max()
}
colnames(SEdistinctVP)[c(2,3,4)] <- paste(c("deaths", "number of animals", "longest time"))


## adding them (as they use different mice):
MMAP$joinedSE <- paste(MMAP$StudyIdStr, MMAP$Experiment)
SEdistinct <- as.data.frame(unique(MMAP$joinedSE))
SEdistinct_missingVN <- SEdistinct %>% filter(!is.element(`unique(MMAP$joinedSE)`,SEdistinctVN$`unique(MMAPVN$joinedSE)`)) %>% select(1)
SEdistinctVN[seq(41,52,1),1] <- SEdistinct_missingVN[seq(1,12,1),1]
SEdistinct_missingVP <- SEdistinct %>% filter(!is.element(`unique(MMAP$joinedSE)`,SEdistinctVP$`unique(MMAPVP$joinedSE)`)) %>% select(1)
SEdistinctVP[seq(17,52,1),1] <- SEdistinct_missingVP[seq(1,36,1),1]
for (se in 1:nrow(SEdistinct)) {
  SEdistinct[se,2] <- SEdistinctVN %>% filter(`unique(MMAPVN$joinedSE)` == SEdistinct[se,1]) %>% select(2)
}
for (se in 1:nrow(SEdistinct)) {
  SEdistinct[se,3] <- SEdistinctVN %>% filter(`unique(MMAPVN$joinedSE)` == SEdistinct[se,1]) %>% select(3)
}
for (se in 1:nrow(SEdistinct)) {
  SEdistinct[se,4] <- SEdistinctVN %>% filter(`unique(MMAPVN$joinedSE)` == SEdistinct[se,1]) %>% select(4)
}
for (se in 1:nrow(SEdistinct)) {
  SEdistinct[se,5] <- SEdistinctVP %>% filter(`unique(MMAPVP$joinedSE)` == SEdistinct[se,1]) %>% select(2)
}
for (se in 1:nrow(SEdistinct)) {
  SEdistinct[se,6] <- SEdistinctVP %>% filter(`unique(MMAPVP$joinedSE)` == SEdistinct[se,1]) %>% select(3)
}
for (se in 1:nrow(SEdistinct)) {
  SEdistinct[se,7] <- SEdistinctVP %>% filter(`unique(MMAPVP$joinedSE)` == SEdistinct[se,1]) %>% select(4)
}
# Building the sum of VN and VP:
SEdistinct$time_match <- ifelse(SEdistinct$`longest time` > 0 | SEdistinct$`longest time.1` > 0, 
                                ifelse(SEdistinct$`longest time` == SEdistinct$`longest time.1`, "match", "no match"),
                                NA)
SEdistinct$deaths_sum <- ifelse(is.na(SEdistinct$time_match),
                                ifelse(is.na(SEdistinct$deaths), SEdistinct$deaths.1, SEdistinct$deaths),
                                SEdistinct$deaths + SEdistinct$deaths.1)
SEdistinct$animals_sum <- ifelse(is.na(SEdistinct$time_match),
                                 ifelse(is.na(SEdistinct$`number of animals`), SEdistinct$`number of animals.1` , SEdistinct$`number of animals`),
                                 SEdistinct$`number of animals` + SEdistinct$`number of animals.1`)
SEdistinct$overall_longest_time <- ifelse(is.na(SEdistinct$time_match),
                                          ifelse(is.na(SEdistinct$`longest time`), SEdistinct$`longest time.1`, SEdistinct$`longest time`),
                                          ifelse(SEdistinct$`longest time` > SEdistinct$`longest time.1`, SEdistinct$`longest time`, SEdistinct$`longest time.1`))


# one row per study:
library(stringr)
SEdistinct$StudyIdStr <- word(SEdistinct$`unique(MMAP$joinedSE)`,1,sep = " ")
SEdistinct$Experiment <- word(SEdistinct$`unique(MMAP$joinedSE)`,2,sep = " ")
MMAP1RS <- SEdistinct %>% select(StudyIdStr) %>% unique()
for (or in 1:nrow(MMAP1RS)) {
  MMAP1RS[or,2] <- SEdistinct %>% filter(SEdistinct$StudyIdStr == MMAP1RS[or,1]) %>% select(9) %>% sum()
}
for (or in 1:nrow(MMAP1RS)) {
  MMAP1RS[or,3] <- SEdistinct %>% filter(SEdistinct$StudyIdStr == MMAP1RS[or,1]) %>% select(10) %>% sum()
}
for (or in 1:nrow(MMAP1RS)) {
  MMAP1RS[or,4] <- SEdistinct %>% filter(SEdistinct$StudyIdStr == MMAP1RS[or,1]) %>% select(11) %>% max()
}
for (or in 1:nrow(MMAP1RS)) {
  MMAP1RS[or,5] <- SEdistinct %>% filter(SEdistinct$StudyIdStr == MMAP1RS[or,1]) %>% select(12) %>% nrow()
}
colnames(MMAP1RS)[seq(2,5,1)] <- c("Deaths","Number_of_mice","Longest_observation_time", "Number_of_experiments")

# meta-analysis with one row per study:
MMAP1Res <- escalc(xi = Deaths, ni = Number_of_mice, measure = "PLO", data = MMAP1RS)
MMAP1Res.logit <- rma(yi, vi, method = "DL", level = 95, data = MMAP1Res)
MMAP1Res.logit.predict <- predict(MMAP1Res.logit, transf=transf.ilogit)
print(MMAP1Res.logit)
print(MMAP1Res.logit.predict, digits = 6)
confint(MMAP1Res.logit)

# Creating a forest plot:
MMAP1RS$author <- paste("Study")
MMAP1RS$year <- seq(1,41,1)
MMAP1RS$authoryear <- paste(MMAP1RS$author," ",MMAP1RS$year)
colnames(MMAP1RS)[c(2,3)] <- paste(c("cases","total"))
# removing one study with NA values:
MMAP1RS <- MMAP1RS %>% filter(StudyIdStr != "40090fa0-6946-4076-ba23-9c5b699a5c6e")
library(meta)
pesMMAP1RS.summary=metaprop(cases, total, authoryear, data=MMAP1RS, sm="PLO")
forest(pesMMAP1RS.summary, sortvar = TE)



### SHAM Mortality

# filtering SHAM mortality data:
MMAS <- MMA %>% filter(ModelLabel == "SHAM")

## only without vehicle control:
MMASVN <- MMAS %>% filter(Vehicle.control. == "")
# Getting on row per study and experiment:
MMASVN$joinedSE <- paste(MMASVN$StudyIdStr,MMASVN$Experiment)
MMASVN$deaths <- as.numeric(MMASVN$deaths)
MMASVN$NumberOfAnimals <- as.numeric(MMASVN$NumberOfAnimals)
MMASVN$Time <-  as.numeric(MMASVN$Time)
SEdistinctVNS <- as.data.frame(unique(MMASVN$joinedSE)) 
for (seVNS in 1:nrow(SEdistinctVNS)) {
  SEdistinctVNS[seVNS,2] <- MMASVN %>% filter(joinedSE == SEdistinctVNS[seVNS,1]) %>% select(deaths) %>% max()
}
for (seVNS in 1:nrow(SEdistinctVNS)) {
  SEdistinctVNS[seVNS,3] <- MMASVN %>% filter(joinedSE == SEdistinctVNS[seVNS,1]) %>% select(NumberOfAnimals) %>% max()
}
for (seVNS in 1:nrow(SEdistinctVNS)) {
  SEdistinctVNS[seVNS,4] <- MMASVN %>% filter(joinedSE == SEdistinctVNS[seVNS,1]) %>% select(Time) %>% max()
}
colnames(SEdistinctVNS)[c(2,3,4)] <- paste(c("deaths", "number of animals", "longest time"))

## only with vehicle control:
MMASVP <- MMAS %>% filter(Vehicle.control. != "")
nrow(MMASVN)+nrow(MMASVP)==nrow(MMAS)
# if its TRUE we can continue
# Getting on row per study and experiment:
MMASVP$joinedSE <- paste(MMASVP$StudyIdStr,MMASVP$Experiment)
SEdistinctVPS <- as.data.frame(unique(MMASVP$joinedSE)) 
for (seVPS in 1:nrow(SEdistinctVPS)) {
  SEdistinctVPS[seVPS,2] <- MMASVP %>% filter(joinedSE == SEdistinctVPS[seVPS,1]) %>% select(deaths) %>% max()
}
for (seVPS in 1:nrow(SEdistinctVPS)) {
  SEdistinctVPS[seVPS,3] <- MMASVP %>% filter(joinedSE == SEdistinctVPS[seVPS,1]) %>% select(NumberOfAnimals) %>% max()
}
for (seVPS in 1:nrow(SEdistinctVPS)) {
  SEdistinctVPS[seVPS,4] <- MMASVP %>% filter(joinedSE == SEdistinctVPS[seVPS,1]) %>% select(Time) %>% max()
}
colnames(SEdistinctVPS)[c(2,3,4)] <- paste(c("deaths", "number of animals", "longest time"))


## adding them (as they use different mice):
MMAS$joinedSE <- paste(MMAS$StudyIdStr, MMAS$Experiment)
SEdistinctS <- as.data.frame(unique(MMAS$joinedSE))
SEdistinct_missingVNS <- SEdistinctS %>% filter(!is.element(`unique(MMAS$joinedSE)`,SEdistinctVNS$`unique(MMASVN$joinedSE)`)) %>% select(1)
SEdistinctVNS[seq(28,37,1),1] <- SEdistinct_missingVN[seq(1,10,1),1]
SEdistinct_missingVPS <- SEdistinctS %>% filter(!is.element(`unique(MMAS$joinedSE)`,SEdistinctVPS$`unique(MMAPVPS$joinedSE)`)) %>% select(1)
SEdistinctVPS[seq(11,47,1),1] <- SEdistinct_missingVPS[seq(1,37,1),1]
for (seS in 1:nrow(SEdistinctS)) {
  SEdistinctS[seS,2] <- SEdistinctVNS %>% filter(`unique(MMASVN$joinedSE)` == SEdistinctS[seS,1]) %>% select(2)
}
for (seS in 1:nrow(SEdistinctS)) {
  SEdistinctS[seS,3] <- SEdistinctVNS %>% filter(`unique(MMASVN$joinedSE)` == SEdistinctS[seS,1]) %>% select(3)
}
for (seS in 1:nrow(SEdistinctS)) {
  SEdistinctS[seS,4] <- SEdistinctVNS %>% filter(`unique(MMASVN$joinedSE)` == SEdistinctS[seS,1]) %>% select(4)
}
for (seS in 1:nrow(SEdistinctS)) {
  SEdistinctS[seS,5] <- SEdistinctVPS %>% filter(`unique(MMASVP$joinedSE)` == SEdistinctS[seS,1]) %>% select(2)
}
for (seS in 1:nrow(SEdistinctS)) {
  SEdistinctS[seS,6] <- SEdistinctVPS %>% filter(`unique(MMASVP$joinedSE)` == SEdistinctS[seS,1]) %>% select(3)
}
for (seS in 1:nrow(SEdistinctS)) {
  SEdistinctS[seS,7] <- SEdistinctVPS %>% filter(`unique(MMASVP$joinedSE)` == SEdistinctS[seS,1]) %>% select(4)
}
# Correction:
SEdistinctS[is.element(SEdistinctS$`unique(MMAS$joinedSE)`,SEdistinctVPS$`unique(MMASVP$joinedSE)`),5] <- 0

# Manually building the sum of VN and VP:
write.csv(SEdistinctS, file = "SEdistinctS1.csv")
SEdistinctS <- read.csv("SEdistinctS_reconciled.csv")

# one row per study:
library(stringr)
SEdistinctS$StudyIdStr <- word(SEdistinctS$unique.MMAS.joinedSE.,1,sep = " ")
SEdistinctS$Experiment <- word(SEdistinctS$unique.MMAS.joinedSE.,2,sep = " ")
MMAS1RS <- SEdistinctS %>% select(StudyIdStr) %>% unique()
for (orS in 1:nrow(MMAS1RS)) {
  MMAS1RS[orS,2] <- SEdistinctS %>% filter(SEdistinctS$StudyIdStr == MMAS1RS[orS,1]) %>% select(9) %>% sum()
}
for (orS in 1:nrow(MMAS1RS)) {
  MMAS1RS[orS,3] <- SEdistinctS %>% filter(SEdistinctS$StudyIdStr == MMAS1RS[orS,1]) %>% select(10) %>% sum()
}
for (orS in 1:nrow(MMAS1RS)) {
  MMAS1RS[orS,4] <- SEdistinctS %>% filter(SEdistinctS$StudyIdStr == MMAS1RS[orS,1]) %>% select(11) %>% max()
}
for (orS in 1:nrow(MMAS1RS)) {
  MMAS1RS[orS,5] <- SEdistinctS %>% filter(SEdistinctS$StudyIdStr == MMAS1RS[orS,1]) %>% select(12) %>% nrow()
}
colnames(MMAS1RS)[seq(2,5,1)] <- c("Deaths","Number_of_mice","Longest_observation_time", "Number_of_experiments")

# meta-analysis with one row per study:
MMAS1Res <- escalc(xi = Deaths, ni = Number_of_mice, measure = "PLO", data = MMAS1RS)
MMAS1Res.logit <- rma(yi, vi, method = "DL", level = 95, data = MMAS1Res)
MMAS1Res.logit.predict <- predict(MMAS1Res.logit, transf=transf.ilogit)
print(MMAS1Res.logit)
print(MMAS1Res.logit.predict, digits = 6)
confint(MMAS1Res.logit)

# Creating a forest plot:
MMAS1RS$author <- paste("Study")
MMAS1RS$year <- seq(1,31,1)
MMAS1RS$authoryear <- paste(MMAS1RS$author," ",MMAS1RS$year)
colnames(MMAS1RS)[c(2,3)] <- paste(c("cases","total"))
# removing the studies with NA values:
MMAS1RS <- MMAS1RS %>% filter(!is.na(MMAS1RS$cases))
# creating a forest plot makes no sense as there are to less cases
write.csv(MMAS1RS, file = "MMAS1RS.csv", row.names = F)




### Meta-regressions of SAH mortality data

## Animal housing conditions

# loading reconciled other housing conditions parameters:
other_housing_cond_parameters <- read.csv("Mice_housing_conditions_parameters.csv")
# adding them to MA
for (m in 1:nrow(MMAP1RS)) {
  MMAP1RS[m,seq(9,14,1)] <- other_housing_cond_parameters[other_housing_cond_parameters == MMAP1RS[m,1],seq(3,8,1)]
}
colnames(MMAP1RS)[seq(9,14,1)] <- paste(c("12-hour light-dark cycle",	"free access to food and water", "controlled humidity",	"controlled temperature",	"temperature (°C)",	"humidity (%)"))
MMAP1RS$`12-hour light-dark cycle` <- ifelse(MMAP1RS$`12-hour light-dark cycle` == "x", TRUE, FALSE)
MMAP1RS$`12-hour light-dark cycle` <- ifelse(is.na(MMAP1RS$`12-hour light-dark cycle`), FALSE, MMAP1RS$`12-hour light-dark cycle`)
MMAP1RS$`free access to food and water` <- ifelse(MMAP1RS$`free access to food and water` == "x", TRUE, FALSE)
MMAP1RS$`free access to food and water` <- ifelse(is.na(MMAP1RS$`free access to food and water`), FALSE, MMAP1RS$`free access to food and water`)
MMAP1RS$`controlled humidity` <- ifelse(MMAP1RS$`controlled humidity` == "x", TRUE, FALSE)
MMAP1RS$`controlled humidity` <- ifelse(is.na(MMAP1RS$`controlled humidity`), FALSE, MMAP1RS$`controlled humidity`)
MMAP1RS$`controlled temperature` <- ifelse(MMAP1RS$`controlled temperature` == "x", TRUE, FALSE)
MMAP1RS$`controlled temperature` <- ifelse(is.na(MMAP1RS$`controlled temperature`), FALSE, MMAP1RS$`controlled temperature`)

# 12-hour light-dark cycle
MMAP1Res <- escalc(xi = Deaths, ni = Number_of_mice, measure = "PLO", data = MMAP1RS)
MMAP1Res.logit12h <- rma(yi, vi, method = "DL", level = 95, mods = ~factor(MMAP1RS$`12-hour light-dark cycle`), data = MMAP1Res)
MMAP1Res.logit.predict12h <- predict(MMAP1Res.logit12h, transf=transf.ilogit)
print(MMAP1Res.logit12h)
confint(MMAP1Res.logit12h)

# free access to food and water
MMAP1Res.logitfood <- rma(yi, vi, method = "DL", level = 95, mods = ~factor(MMAP1RS$`free access to food and water`), data = MMAP1Res)
MMAP1Res.logit.predictfood <- predict(MMAP1Res.logitfood, transf=transf.ilogit)
print(MMAP1Res.logitfood)
confint(MMAS1Res.logit)

# controlled temperature
MMAP1Res.logitCT <- rma(yi, vi, method = "DL", level = 95, mods = ~factor(MMAP1RS$`controlled temperature`), data = MMAP1Res)
MMAP1Res.logit.predictCT <- predict(MMAP1Res.logitCT, transf=transf.ilogit)
print(MMAP1Res.logitCT)
confint(MMAP1Res.logitCT)

# controlled humidity
MMAP1Res.logitCH <- rma(yi, vi, method = "DL", level = 95, mods = ~factor(MMAP1RS$`controlled humidity`), data = MMAP1Res)
MMAP1Res.logit.predictCH <- predict(MMAP1Res.logitCT, transf=transf.ilogit)
print(MMAP1Res.logitCH)
confint(MMAP1Res.logitCH)


## mouse age:

# adding them to MA
for (m in 1:nrow(MMAP1RS)) {
  MMAP1RS[m,15] <- mice_age_reconciled_overview[mice_age_reconciled_overview$StudyID == MMAP1RS[m,1],4]
}
colnames(MMAP1RS)[15] <- paste("age_median")
MMAP1RS[MMAP1RS$StudyIdStr == "2ea6da77-9ff3-41a6-9ad5-a46de336416b", 15] <- NA
MMAP1RS$age_median <- ifelse(MMAP1RS$age_median < 0.01, NA, MMAP1RS$age_median)
MMAP1RS$age_median <- as.numeric(MMAP1RS$age_median)

# meta-regression:
MMAP1Res.logitage <- rma(yi, vi, method = "DL", level = 95, mods = ~MMAP1RS$age_median, data = MMAP1Res)
MMAP1Res.logit.predictage <- predict(MMAP1Res.logitage, transf=transf.ilogit)
print(MMAP1Res.logitage)
confint(MMAP1Res.logitage)


## Mice weight

# adding them to MA
for (m in 1:nrow(MMAP1RS)) {
  MMAP1RS[m,16] <- mice_weight_reconciled_overview[mice_weight_reconciled_overview$StudyID == MMAP1RS[m,1],4]
}
colnames(MMAP1RS)[16] <- paste("weight_median")
MMAP1RS$weight_median <- as.numeric(MMAP1RS$weight_median)

# meta-regression:
MMAP1Res.logitwt <- rma(yi, vi, method = "DL", level = 95, mods = ~MMAP1RS$weight_median, data = MMAP1Res)
MMAP1Res.logit.predictwt <- predict(MMAP1Res.logitwt, transf=transf.ilogit)
print(MMAP1Res.logitwt)
confint(MMAP1Res.logitwt)


## Type of anesthesia
# Anesthesia
for (m in 1:nrow(MMAP1RS)) {
  MMAP1RS[m,17] <- SA[SA$StudyIdStr == MMAP1RS[m,1],17]
}
colnames(MMAP1RS)[17] <- paste("type of anesthesia")

# meta-regression:
MMAP1Res.logitAnes <- rma(yi, vi, method = "DL", level = 95, mods = ~factor(MMAP1RS$`type of anesthesia`), data = MMAP1Res)
MMAP1Res.logit.predictANes <- predict(MMAP1Res.logitAnes, transf=transf.ilogit)
print(MMAP1Res.logitAnes)
confint(MMAP1Res.logitAnes)


## Injective anesthesia substance
for (m in 1:nrow(MMAP1RS)) {
  MMAP1RS[m,18] <- Injective_anesthetics_reconciled_overview[Injective_anesthetics_reconciled_overview$StudyID == MMAP1RS[m,1],3]
}
colnames(MMAP1RS)[18] <- paste("injetive_anesthetic_substance")

# meta-regression:
MMAP1Res.logitIAS <- rma(yi, vi, method = "DL", level = 95, mods = ~factor(MMAP1RS$injetive_anesthetic_substance), data = MMAP1Res)
MMAP1Res.logit.predictIAS <- predict(MMAP1Res.logitIAS, transf=transf.ilogit)
print(MMAP1Res.logitIAS)
confint(MMAP1Res.logitIAS)


## Intubation
for (m in 1:nrow(MMAP1RS)) {
  MMAP1RS[m,19] <- SA[SA$StudyIdStr == MMAP1RS[m,1],5]
}
colnames(MMAP1RS)[19] <- paste("intubation")

# meta-regression:
MMAP1Res.logitInt <- rma(yi, vi, method = "DL", level = 95, mods = ~factor(MMAP1RS$intubation), data = MMAP1Res)
MMAP1Res.logit.predictInt <- predict(MMAP1Res.logitInt, transf=transf.ilogit)
print(MMAP1Res.logitInt)
confint(MMAP1Res.logitInt)


## Vessel of perforation
for (m in 1:nrow(MMAP1RS)) {
  MMAP1RS[m,20] <- perforation_location_reconciled_overview[perforation_location_reconciled_overview$StudyID == MMAP1RS[m,1],4]
}
colnames(MMAP1RS)[20] <- paste("vessel_perforation")

# meta-regression:
MMAP1Res.logitVP <- rma(yi, vi, method = "DL", level = 95, mods = ~factor(MMAP1RS$vessel_perforation), data = MMAP1Res)
MMAP1Res.logit.predictVP <- predict(MMAP1Res.logitVP, transf=transf.ilogit)
print(MMAP1Res.logitVP)
confint(MMAP1Res.logitVP)


## Postsurgical pain/stress-management (yes/no)
for (m in 1:nrow(MMAP1RS)) {
  MMAP1RS[m,21] <- SA[SA$StudyIdStr == MMAP1RS[m,1],11]
}
colnames(MMAP1RS)[21] <- paste("postsurgical treatment")

# meta-regression:
MMAP1Res.logitPST <- rma(yi, vi, method = "DL", level = 95, mods = ~factor(MMAP1RS$`postsurgical treatment`), data = MMAP1Res)
MMAP1Res.logit.predictPST <- predict(MMAP1Res.logitPST, transf=transf.ilogit)
print(MMAP1Res.logitPST)
confint(MMAP1Res.logitPST)


## ICP monitoring (yes/no)
for (m in 1:nrow(MMAP1RS)) {
  MMAP1RS[m,22] <- SA[SA$StudyIdStr == MMAP1RS[m,1],13]
}
colnames(MMAP1RS)[22] <- paste("ICP monitoring")

# meta-regression:
MMAP1Res.logitICP <- rma(yi, vi, method = "DL", level = 95, mods = ~factor(MMAP1RS$`ICP monitoring`), data = MMAP1Res)
MMAP1Res.logit.predictICP <- predict(MMAP1Res.logitICP, transf=transf.ilogit)
print(MMAP1Res.logitICP)
confint(MMAP1Res.logitICP)


## Filament size
for (m in 1:nrow(MMAP1RS)) {
  MMAP1RS[m,23] <- SA[SA$StudyIdStr == MMAP1RS[m,1],16]
}
colnames(MMAP1RS)[23] <- paste("filament size")

# meta-regression:
MMAP1Res.logitFS <- rma(yi, vi, method = "DL", level = 95, mods = ~factor(MMAP1RS$`filament size`), data = MMAP1Res)
MMAP1Res.logit.predictFS <- predict(MMAP1Res.logitFS, transf=transf.ilogit)
print(MMAP1Res.logitFS)
confint(MMAP1Res.logitFS)


## Filament material
# adding them to MA
for (m in 1:nrow(MMAP1RS)) {
  MMAP1RS[m,seq(24,30,1)] <- filament_types_reconciled_overview[filament_types_reconciled_overview$StudyID == MMAP1RS[m,1],seq(4,10,1)]
}
colnames(MMAP1RS)[seq(24,30,1)] <- paste(c("material","lenght", "diameter",	"sharpened tip", "blunted tip", "monofilament",	"suture"))

# meta-regression:
MMAP1Res.logitFM <- rma(yi, vi, method = "DL", level = 95, mods = ~factor(MMAP1RS$material), data = MMAP1Res)
MMAP1Res.logit.predictFM <- predict(MMAP1Res.logitFM, transf=transf.ilogit)
print(MMAP1Res.logitFM)
confint(MMAP1Res.logitFM)


## Filament tip
MMAP1RS$blunted_sharpened <- ifelse(MMAP1RS$`sharpened tip` == "x","sharpened", 
                                    ifelse(MMAP1RS$`blunted tip` == "x", "blunted","not reported"))

# meta-regression:
MMAP1Res.logitFT <- rma(yi, vi, method = "DL", level = 95, mods = ~factor(MMAP1RS$blunted_sharpened), data = MMAP1Res)
MMAP1Res.logit.predictFT <- predict(MMAP1Res.logitFT, transf=transf.ilogit)
print(MMAP1Res.logitFT)
confint(MMAP1Res.logitFT)


## Vehicle control
write.csv(MMAPVP, file = "MMAPVP.csv", row.names = F)
write.csv(MMAPVN, file = "MMAPVN.csv", row.names = F)
MMAPVP1RS <- read.csv("MMAPVP1RS.csv")
MMAPVN1RS <- read.csv("MMAPVN1RS.csv")
# combine both into one dataframe:
all(colnames(MMAPVP1RS) == colnames(MMAPVN1RS))
MMAPVP1RS$vehicle <- "yes"
MMAPVN1RS$vehicle <- "no"
MMAPVC1RS <- rbind(MMAPVN1RS, MMAPVP1RS)

# Subgroup analysis
# Assumption 1: Do not assume a common between-study variance component (do not pool within-group estimates of between-study variance)
# Logit transformation
pes.logit.subgroupVP=rma(deaths, NumberOfAnimals, data=MMAPVC1RS, subset=vehicle=="yes")
pes.logit.subgroupVN=rma(deaths, NumberOfAnimals, data=MMAPVC1RS, subset=vehicle=="no")
pes.subgroupVP=predict(pes.logit.subgroupVP, transf=transf.ilogit)
pes.subgroupVN=predict(pes.logit.subgroupVN, transf=transf.ilogit)
dat.diffvarVC=data.frame(estimate=c(pes.logit.subgroupVP$b, pes.logit.subgroupVN$b),
                       stderror=c(pes.logit.subgroupVP$se, pes.logit.subgroupVN$se),
                       moderator=c("yes", "no"),
                       tau2=round(c(pes.logit.subgroupVP$tau2,
                                    pes.logit.subgroupVN$tau2), 3))
subganal.moderatorVC=rma(estimate, sei=stderror, mods=~moderator,
                       method="FE", data=dat.diffvarVC)
pes.logit.moderatorVC=rma(estimate, sei=stderror, method="FE", data=dat.diffvarVC)
pes.moderatorVC=predict(pes.logit.moderatorVC, transf=transf.ilogit)
print(pes.subgroupVP); print(pes.logit.subgroupVP) 
print(pes.subgroupVN); print(pes.logit.subgroupVN)
print(subganal.moderatorVC)
print(pes.moderatorVC)


## Time

# data preparations (Time 1,2,3)
write.csv(MMAP1, file = "MMAP1.csv", row.names = F)
write.csv(MMAP2, file = "MMAP2.csv", row.names = F)
write.csv(MMAP3, file = "MMAP3.csv", row.names = F)
MMAP11RS <- read.csv("MMAP11RS.csv")
MMAP21RS <- read.csv("MMAP21RS.csv")
MMAP31RS <- read.csv("MMAP31RS.csv")
MMAP1231RS <- rbind(MMAP11RS, MMAP21RS, MMAP31RS)
# subgroup analysis
pes.logit.subgroupTime1=rma(deaths, NumberOfAnimals, data=MMAP1231RS, subset=Time==1)
pes.logit.subgroupTime2=rma(deaths, NumberOfAnimals, data=MMAP1231RS, subset=Time==2)
pes.logit.subgroupTime3=rma(deaths, NumberOfAnimals, data=MMAP1231RS, subset=Time==3)
pes.subgroupTime1=predict(pes.logit.subgroupTime1, transf=transf.ilogit)
pes.subgroupTime2=predict(pes.logit.subgroupTime2, transf=transf.ilogit)
pes.subgroupTime3=predict(pes.logit.subgroupTime3, transf=transf.ilogit)
dat.diffvarTime=data.frame(estimate=c(pes.logit.subgroupTime1$b, pes.logit.subgroupTime2$b, pes.logit.subgroupTime3$b),
                         stderror=c(pes.logit.subgroupTime1$se, pes.logit.subgroupTime2$se, pes.logit.subgroupTime3$se),
                         moderator=c(1,2,3),
                         tau2=round(c(pes.logit.subgroupTime1$tau2,
                                      pes.logit.subgroupTime2$tau2,
                                      pes.logit.subgroupTime3$tau2), 3))
subganal.moderatorTime=rma(estimate, sei=stderror, mods=~moderator,
                         method="FE", data=dat.diffvarTime)
pes.logit.moderatorTime=rma(estimate, sei=stderror, method="FE", data=dat.diffvarTime)
pes.moderatorTime=predict(pes.logit.moderatorTime, transf=transf.ilogit)
print(pes.subgroupTime1); print(pes.logit.subgroupTime1) 
print(pes.subgroupTime2); print(pes.logit.subgroupTime2)
print(pes.subgroupTime3); print(pes.logit.subgroupTime3)
print(subganal.moderatorTime)
print(pes.moderatorTime)



# Time = 1
MMAPTime1Res <- escalc(xi = deaths, ni = NumberOfAnimals, measure = "PLO", data = MMAP11RS)
MMAS1Res.logitTime1 <- rma(yi, vi, method = "DL", level = 95, data = MMAPTime1Res)
MMAS1Res.logit.predictTime1 <- predict(MMAS1Res.logitTime1, transf=transf.ilogit)
print(MMAS1Res.logitTime1)
print(MMAS1Res.logit.predictTime1, digits = 6)
confint(MMAS1Res.logitTime1)

# Time = 2
MMAPTime2Res <- escalc(xi = deaths, ni = NumberOfAnimals, measure = "PLO", data = MMAP21RS)
MMAS1Res.logitTime2 <- rma(yi, vi, method = "DL", level = 95, data = MMAPTime2Res)
MMAS1Res.logit.predictTime2 <- predict(MMAS1Res.logitTime2, transf=transf.ilogit)
print(MMAS1Res.logitTime2)
print(MMAS1Res.logit.predictTime2, digits = 6)
confint(MMAS1Res.logitTime2)

# Time = 3
MMAPTime3Res <- escalc(xi = deaths, ni = NumberOfAnimals, measure = "PLO", data = MMAP31RS)
MMAS1Res.logitTime3 <- rma(yi, vi, method = "DL", level = 95, data = MMAPTime3Res)
MMAS1Res.logit.predictTime3 <- predict(MMAS1Res.logitTime3, transf=transf.ilogit)
print(MMAS1Res.logitTime3)
print(MMAS1Res.logit.predictTime3, digits = 6)
confint(MMAS1Res.logitTime3)


## Including all timepoints
MMAPTimeother <- MMAP %>% filter(Time != 1 & Time != 2 & Time != 3)
write.csv(MMAPTimeother, file = "MMAPTimeother.csv", row.names = F)
MMAPTimeother1RS <- read.csv("MMAPTimeother1RS.csv")
MMAPTimes1RS <- rbind(MMAP11RS, MMAP21RS, MMAP31RS, MMAPTimeother1RS)

# meta regression:
MMAPTimesRes <- escalc(xi = deaths, ni = NumberOfAnimals, measure = "PLO", data = MMAPTimes1RS)
MMAS1Res.logitTimes <- rma(yi, vi, method = "DL", level = 95, mods = ~Time ,data = MMAPTimesRes)
MMAS1Res.logit.predictTimes <- predict(MMAS1Res.logitTimes, transf=transf.ilogit)
print(MMAS1Res.logitTimes)
print(MMAS1Res.logit.predictTimes, digits = 6)
confint(MMAS1Res.logitTimes)





#### SAH grade
GMA <- MA %>% filter(Which.type.of.outcome.was.assessed. == "SAH grade")
table(GMA$SAH.Grading.System)

# one row per study:
write.csv(GMA, file = "GMA.csv", row.names = F)
GMArec1RS <- read.csv("GMArec.csv")
# filter Model = SAH and grading method = Sugawara:
GMASS <- GMArec1RS %>% filter(ModelLabel == "SAH") %>% filter(SAH_grading_summarized == "Sugawara 2008")
write.csv(GMASS, file = "GMASS.csv",  row.names = F)
# only one timepoint and row per study (the timepoint with the highest number of animals was taken, data from multiple experiments at the same timepoit were summarized)
GMASS1RS <- read.csv("GMASS1RS.csv")
GMASS1RS$SD <- ifelse(GMASS1RS$ErrorType == "SD", GMASS1RS$Error, GMASS1RS$Error*sqrt(GMASS1RS$NumberOfAnimals))
GMASS1RS$variance <- GMASS1RS$SD^2
GMASS1RS <- GMASS1RS[order(GMASS1RS$Average),]

## Meta-analysis (SAh score is effect size)
rma(yi=Average, vi=variance, method = "REML"  ,data = GMASS1RS)
forest(rma(yi=Average, vi=variance, method = "REML"  ,data = GMASS1RS),xlim = c(0,18))

# Forest plot:
library(meta)
pesGMASS1RS.summary=rma(yi=Average, vi=variance, method = "REML"  ,data = GMASS1RS)
forest(pesGMASS1RS.summary, xlim = c(0,18))





#### Vasospasm
VMA <- MA %>% filter(Which.type.of.outcome.was.assessed. != "Mortality rate (%)", Which.type.of.outcome.was.assessed. != "SAH grade")
write.csv(VMA, file = "VMA.csv", row.names = F)
# calculate effect size (raw mean difference)
SAH_vasospasm_sham_ratio <- read.csv("SAH_vasospasm_sham_ratio.csv")
SAHvasospasmRMD <- escalc(measure = "MD",n1i = SAH_vasospasm_sham_ratio$NumberofAnimalsSHAM, n2i = SAH_vasospasm_sham_ratio$NumberOfAnimals, m1i = SAH_vasospasm_sham_ratio$AverageSHAM, m2i = SAH_vasospasm_sham_ratio$Average, sd1i = SAH_vasospasm_sham_ratio$SDSHAM, sd2i = SAH_vasospasm_sham_ratio$SD, data = SAH_vasospasm_sham_ratio)
SAHvasospasmRMD$sdi <- sqrt(SAHvasospasmRMD$vi)
# manually adding SD values because of unreported number of animals (conservative estimations)
SAHvasospasmRMD[2,78] <- 12
SAHvasospasmRMD[3,78] <- 15
# adding a column with procentual change:
SAHvasospasmRMD$yiprocent <- SAHvasospasmRMD$yi / SAHvasospasmRMD$AverageSHAM
SAHvasospasmRMD$sdiprocent <- SAHvasospasmRMD$sdi / SAHvasospasmRMD$AverageSHAM
# filtering only the relevant columns:
SAHvasospasmrelative <- SAHvasospasmRMD[,c(1,6,9,11,13,18,79,80)]
write.csv(SAHvasospasmrelative, file = "SAHvasospasmrelative1.csv", row.names = F)
# converting percent values back into numerical for meta-analysis:
SAHvasospasmrelativeNP <- SAHvasospasmrelative
SAHvasospasmrelativeNP$vi <- SAHvasospasmrelativeNP$sdiprocent^2
colnames(SAHvasospasmrelativeNP)[c(7,8)] <- paste(c("yi","sdi"))

## meta-analysis inclunding all data from all vessels and studies (excl. duplicate data of different outcome assessment method in one article):

# two-level MA
SAHvasospasmrelativeNP <- SAHvasospasmrelativeNP %>% filter(DiameterMeasurementMethodSHAM != "CT")
rma(yi,vi, method = "REML",data = SAHvasospasmrelativeNP)

# three-level MA
SAHvasospasmrelativeNP$rn <- row_number(SAHvasospasmrelativeNP$StudyIdStr)
VMA3L <- rma.mv(yi,vi, random = list(~ 1 | rn, ~ 1 | StudyIdStr), method = "REML", data = SAHvasospasmrelativeNP)
coef_test(VMA3L, vcov = "CR2", cluster = SAHvasospasmrelativeNP$StudyIdStr)
conf_int(VMA3L, vcov = "CR2", cluster = SAHvasospasmrelativeNP$StudyIdStr)
i2_ml(VMA3L)

# Three-level MR Vessel
VMA3LVessel <- rma.mv(yi,vi, random = list(~ 1 | rn, ~ 1 | StudyIdStr), mods = ~factor(VesselSHAM),method = "REML", data = SAHvasospasmrelativeNP)
VMA3LVessel

# Three-level MR Vessel Side
VMA3LSide <- rma.mv(yi,vi, random = list(~ 1 | rn, ~ 1 | StudyIdStr), mods = ~factor(SideSHAM),method = "REML", data = SAHvasospasmrelativeNP)
VMA3LSide

# Three-level MR Time
VMA3LTime <- rma.mv(yi,vi, random = list(~ 1 | rn, ~ 1 | StudyIdStr), mods = ~TimeSHAM,method = "REML", data = SAHvasospasmrelativeNP)
VMA3LTime 
regplot(VMA3LTime, xlab = "Time", ylab = "Vasospasm (SAH/SHAM)")