###### SAH perforation model Systematic Review and Meta-analysis ###########



### Loading/preparing data exported from SyRF

# Setting working directory:
setwd("/users/tsand/desktop/SAH project Meta-analysis data R Code/")

# Loading libraries used for further calculations:
library(dplyr)
library(plyr)
library(readr)
library(tidyverse)
library(scales)
library(metafor)
library(clubSandwich)
library(orchaRd)
library(meta)
library(stringr)


# Loading reconciled study annotations:
SA <- read.csv("SAH study annotations reconciliation.csv")
# Filter only the reconciled annotations:
SA <- SA %>% filter(AnnotatorIdStr == "TIMO")

# Loading reconciled outcome annotations:
OA <- read.csv("SAH outcome reconciliation.csv")
# Filter only the reconciled annotations:
OA <- OA %>% filter(AnnotatorIdStr == "TIMO")

# Number of included articles:
SA %>% select(3) %>% unique() %>% nrow()
OA %>% select(1) %>% unique() %>% nrow()

# Are there articles that are an element of OA but not SA:
OA %>% filter(!is.element(StudyIdStr,SA$StudyIdStr)) %>% select(1)
# No

# Removing articles that have no outcome annotations (which means they got excluded) from SA:
SA <- SA %>% filter(is.element(StudyIdStr,OA$StudyIdStr))

# Updated number of included articles:
SA %>% select(3) %>% unique() %>% nrow()
OA %>% select(1) %>% unique() %>% nrow()


## Removing irrelevant columns from SA and OA

# Loading a manually created list of irrelevant columns of the file that was generated by SyRF:
Irrelevant_columns <- read.csv("List of columns to remove from SAH annotations.csv")

# Removing NA values:
Irrelevant_columns_study <- Irrelevant_columns %>% filter(Study != "NA") %>% select(1) %>% toString()
Irrelevant_columns_outcomes <- Irrelevant_columns %>% filter(Outcomes != "NA") %>% select(2) %>% toString()

# Removing irrelevant columns from SA:
SA <- SA[,-c(1, 2, 6, 7, 9, 10, 12, 15, 18, 19, 21, 22, 24, 27, 30, 31, 33, 34, 36, 39, 42, 45, 46, 48, 51, 54, 57, 60, 63, 64, 66, 69, 70, 72, 73, 75, 76, 78, 79, 81, 82, 84, 85, 87, 88, 90, 93, 94, 96, 99, 100, 102, 103, 105, 108, 109, 111, 112, 114, 115, 117, 118, seq(119,176,1))]

# Removing irrelevant columns from OA:
OA <- OA[,-c(3, 4, 5, 6, 7, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 68, 69, 70, 71, 72, 74, 75, 76, 77, 78, 79, 80, 81,seq(90,1024,1))]




##### Analysis of study annotation parameters

# As we only have one parameter phenotype per study, we can let us show the tables of the parameters in SA


### Mouse parameters

# Strain
table(SA$X18379abd.003c.4af8.8186.91b5c45b2c65_Which.mouse.strain.was.used.)

# Sex
table(SA$X1b642852.1651.4649.8659.ceb696562040_What.are.the.information.on.mice.sex.)

# Age
table(SA$X847f84e6.8338.45b9.81f0.7a578f6ff564_What.is.the.age.of.the.mice.) %>% as.data.frame() %>% write.csv("mice_age1.csv", row.names = F)

# Weight
table(SA$a519b196.b50e.4e4d.bfa9.5e01e6157ad8_How.was.the.weight.of.the.mice.)  %>% as.data.frame() %>% write.csv("mice_weight1.csv", row.names = F)

# Animals with immunodepression used?
table(SA$X740b1a07.0128.4e83.b958.a721e289f57a_Were.animals.with.immunodepression.used.for.experiments.)



### Animal housing conditions

# Single vs. group cage
table(SA$X63c6d74f.9c40.4ee4.b929.110a1b46dba8_How.were.the.animal.housing.conditions.described.)

# Other housing condition parameters
table(SA$X78b2e595.fe44.4727.9a0c.664e936af6e1_How.were.the.other.animal.housing.conditions.described.) %>% as.data.frame() %>% write.csv("other_housing_conditions1.csv", row.names = F)



### Anaesthesia

# Type
table(SA$X552b6157.e446.49ad.90c1.09ee1c4f929d_How.were.the.mice.anaesthetised.)

# Other types
table(SA$X90048d0f.3575.4024.9cc6.72d98225efbf_Which.other.anaesthetical.procedure.was.used.)

# Inhalative anaesthetics
table(SA$acd50172.1d29.4bf1.a5ec.e5320c86e83f_Which.inhalative.anaesthetic.was.used.) %>% as.data.frame() %>% write.csv("inhalative_anaesthetic1.csv", row.names = F)

# Injective anaesthetics
table(SA$X75220509.5fa4.4765.94f0.b1b618b8da28_Which.intravenous.anaesthetic.was.used.) %>% as.data.frame() %>% write.csv("injective_anaesthetics1.csv", row.names = F)

# Intubation
table(SA$X1576fbb4.2a1a.4ed0.ba1e.9760ae3e8cff_Were.the.mice.intubated.)



### Surgery

# Filament entry point
table(SA$feef2370.3b71.4e0c.9724.8c0c3eba7970_Where.was.the.perforation.entry.point.) %>% as.data.frame() %>% write.csv("perforation_entry1.csv", row.names = F)

# Location of perforation
table(SA$X7cf59b31.bba7.4207.8ff5.750bec9bfd9c_Where.was.the.location.of.perforation.) %>% as.data.frame() %>% write.csv("perforation_location1.csv", row.names = F)

# Duration of surgery
table(SA$efea8113.a97b.4bb6.8940.2205a6b5b482_How.long.was.the.duration.of.surgical.treatment.of.perforation.)

# Monitoring of ICP
table(SA$X35ac3c0e.ce1b.46b7.b6c1.13f58f6bd78a_Was.intracranial.pressure.montitored.)

# Postsurgical pain/stress-management reporting
table(SA$X29507fcf.6301.423d.8d54.ea3e700a2e46_Were.any.methods.to.reduce.postsurgical.pain.stress.of.mice.reported)

# Detailed postsurgical pain/stress-management
table(SA$c76b9578.c4de.47cf.adad.1829bf125b1e_Which.methods.to.reduce.postsurgical.pain.stress.of.mice.were.used.) %>% as.data.frame() %>% write.csv("postsurgical_treatment1.csv", row.names = F)



### Filament

# Diameter
table(SA$X4ee728ab.4cb9.444e.96ae.c2e96b1864a9_What.was.the.size.of.the.filament.used.for.perforation.model.)

# Type
table(SA$X799fbc30.2d1d.4713.a549.9f0a56bdd329_Which.filament.was.used.for.perforation.model.)

# Other filament types
table(SA$X9d26e1f7.7cc8.4cd8.be95.ab5576e4cb13_Which.other.filament.type.was.used.for.perforation.model.) %>% as.data.frame() %>% write.csv("filament_types1.csv", row.names = F)





##### Analysis of outcome related parameters

### Number of studies/experiments per outcome

# Total experiments including all three outcomes:
OA %>% distinct(StudyIdStr, Experiment) %>% unique() %>% nrow()

# How many studies have reported mortality?
OA %>% filter(Which.type.of.outcome.was.assessed. == "Mortality rate (%)") %>% select(StudyIdStr) %>% unique() %>% nrow()

# How many studies have reported SAH grade?
OA %>% filter(Which.type.of.outcome.was.assessed. == "SAH grade") %>% select(StudyIdStr) %>% unique() %>% nrow()

# How many studies have reported vasospasm?
OA %>% filter(Which.type.of.outcome.was.assessed. != "Mortality rate (%)", Which.type.of.outcome.was.assessed. != "SAH grade") %>% select(StudyIdStr) %>% unique() %>% nrow()

# How many experiments have reported mortality?
OA %>% filter(Which.type.of.outcome.was.assessed. == "Mortality rate (%)") %>% distinct(StudyIdStr, Experiment) %>% unique() %>% nrow()

# How many experiments have reported SAH grade?
OA %>% filter(Which.type.of.outcome.was.assessed. == "SAH grade") %>% distinct(StudyIdStr, Experiment) %>% unique() %>% nrow()

# How many experiments have reported vasospasm?
OA %>% filter(Which.type.of.outcome.was.assessed. != "Mortality rate (%)", Which.type.of.outcome.was.assessed. != "SAH grade") %>% distinct(StudyIdStr, Experiment) %>% unique() %>% nrow()



### Vehicle controls

# Number of articles with vehicle controls
OA %>% filter(Vehicle.control. != "") %>% select(1) %>% unique() %>% nrow()

# Number of experiments with vehicle controls
OA %>% filter(Vehicle.control. != "") %>% distinct(StudyIdStr, Experiment) %>% unique() %>% nrow()



### SAH grading systems

# Number of articles per SAH grading system:
OA %>% filter(Reconciled.SAH.grading.system != "") %>% distinct(StudyIdStr, .keep_all = TRUE) %>% select(18) %>% table()

# Number of experiments per SAH grading system:
OA %>% filter(Reconciled.SAH.grading.system != "") %>% distinct(StudyIdStr, Experiment, .keep_all = TRUE) %>% select(18) %>% table()





##### Exclusions from Meta-analysis

# The only reason for exclusion is an unreported number of animals

### Unreported number of animals

# all NA values stand for unreported number of animals
OA$NumberOfAnimals <- as.numeric(OA$NumberOfAnimals)
OA %>% filter(is.na(NumberOfAnimals))

# there is one articles that has to be excluded:
# 2f3c1ffb-db00-4396-81d1-2051871f6170: only one experiment of mortality needs to be excluded -> the other experiment with mortality data ramains in Meta-analysis
# 40090fa0-6946-4076-ba23-9c5b699a5c6e: gets completely excluded (reported only mortality)
# 4e20f054-08ef-4296-994e-6ca213e76698: vasospasm data completely excluded, mortality data remain

# Remove the data with unreported number of animals from Meta-analysis data sheet:
MA <- OA %>% filter(!is.na(NumberOfAnimals))





##### Adding study parameters to outcomes for meta-analysis

# Previously loading an updated study annotations sheet with the reconciled mouse strains:
SA <- read.csv("SA.csv")

# Adding two placeholder columns
MA[,22:23] <- "NA"

# Intubation
for (c in 1:nrow(MA)) {
  MA[c,24] <- SA[SA$StudyIdStr == MA[c,1],5]
}
colnames(MA)[24] <- paste("intubation")

# Mouse strain
for (c in 1:nrow(MA)) {
  MA[c,25] <- SA[SA$StudyIdStr == MA[c,1],57]
}
colnames(MA)[25] <- paste("strain")

# Presence of Postsurgical stress/pain-management
SA[SA$StudyIdStr == "4c4e2785-7a37-4372-a212-00a99a93b34a",11] <- "Reported that no postsurgical treatment was given"
for (c in 1:nrow(MA)) {
  MA[c,26] <- SA[SA$StudyIdStr == MA[c,1],11]
}
colnames(MA)[26] <- paste("postsurgical treatment")

# ICP monitoring
for (c in 1:nrow(MA)) {
  MA[c,27] <- SA[SA$StudyIdStr == MA[c,1],13]
}
colnames(MA)[27] <- paste("ICP monitoring")

# Filament size
SA[SA$X4ee728ab.4cb9.444e.96ae.c2e96b1864a9_What.was.the.size.of.the.filament.used.for.perforation.model. == 0, 16] <- "not reported"
SA[SA$X4ee728ab.4cb9.444e.96ae.c2e96b1864a9_What.was.the.size.of.the.filament.used.for.perforation.model. == "5-0 monofilament",16] <- "5-0"
for (c in 1:nrow(MA)) {
  MA[c,28] <- SA[SA$StudyIdStr == MA[c,1],16]
}
colnames(MA)[28] <- paste("filament size")

# Anesthesia
SA[SA$X552b6157.e446.49ad.90c1.09ee1c4f929d_How.were.the.mice.anaesthetised. == "Other",17] <- "Injective and inhalative anaesthesia combined"
for (c in 1:nrow(MA)) {
  MA[c,29] <- SA[SA$StudyIdStr == MA[c,1],17]
}
colnames(MA)[29] <- paste("type of anesthesia")

# Single or group cage
SA[SA$X63c6d74f.9c40.4ee4.b929.110a1b46dba8_How.were.the.animal.housing.conditions.described. == "group",58] <- "group cage"
SA[SA$X63c6d74f.9c40.4ee4.b929.110a1b46dba8_How.were.the.animal.housing.conditions.described. == "single cage",58] <- "single cage"
SA[is.na(SA$V58),58] <- "not reported whether single or group cage"
colnames(SA)[58] <- paste("Singe/Group cage")
for (c in 1:nrow(MA)) {
  MA[c,30] <- SA[SA$StudyIdStr == MA[c,1],58]
}
colnames(MA)[30] <- paste("Singe/Group cage")


## Other housing condition parameters:

# Writing csv for manual reconciliation:
write.csv(SA$X78b2e595.fe44.4727.9a0c.664e936af6e1_How.were.the.other.animal.housing.conditions.described., file = "other_housing_conditions_match1.csv")
SA %>% select(1,22,28) %>% write.csv(file = "other_housing_conditions_match1.csv", row.names = F)

# Loading reconciled other housing conditions parameters:
other_housing_cond_parameters <- read.csv("Mice_housing_conditions_parameters.csv")

# Adding them to MA
for (c in 1:nrow(MA)) {
  MA[c,seq(31,36,1)] <- other_housing_cond_parameters[other_housing_cond_parameters == MA[c,1],seq(3,8,1)]
}
colnames(MA)[seq(31,36,1)] <- paste(c("12-hour light-dark cycle",	"free access to food and water", "controlled humidity",	"controlled temperature",	"temperature (C)",	"humidity (%)"))


## Injective Anesthetics

# Writing csv for manual reconciliation:
write.csv(SA[,c(1,26)], file = "injective_anesthetics_overview1.csv", row.names = F)

# Loading reconciled data:
Injective_anesthetics_reconciled_overview <- read.csv("Injective_anesthetics_reconciled_overview.csv")

# Adding them to MA
for (c in 1:nrow(MA)) {
  MA[c,seq(37,38,1)] <- Injective_anesthetics_reconciled_overview[Injective_anesthetics_reconciled_overview == MA[c,1],seq(3,4,1)]
}
colnames(MA)[seq(37,38,1)] <- paste(c("injetive_anesthetic_substance",	"injetive_anesthetic_dose"))


## Inhalative Anesthetics

# Writing csv for manual reconciliation:
write.csv(SA[,c(1,44)], file = "inhalative_anesthetics_overview.csv", row.names = F)

# Loading reconciled data:
Inhalative_anesthetics_reconciled_overview <- read.csv("Inhalative_anesthetics_reconciled_overview.csv")

# Adding them to MA
for (c in 1:nrow(MA)) {
  MA[c,seq(39,43,1)] <- Inhalative_anesthetics_reconciled_overview[Inhalative_anesthetics_reconciled_overview$X == MA[c,1],seq(2,6,1)]
}
colnames(MA)[seq(39,43,1)] <- paste(c("Inhalative anesthesiea Substance",	"Isoflurane Induction",	"Isoflurane Maintenance", "Inhalative Anesthesia O2/N2-Mixture",	"Inhalative Anesthesia Flow"))


## Filament type

# Writing csv for manual reconciliation:
write.csv(SA[,c(1,40)], file = "filament_types_overview.csv", row.names = F)

# Loading reconciled data:
filament_types_reconciled_overview <- read.csv("filament_types_reconciled_overview.csv")

# Adding them to MA
for (c in 1:nrow(MA)) {
  MA[c,seq(44,50,1)] <- filament_types_reconciled_overview[filament_types_reconciled_overview$StudyID == MA[c,1],seq(4,10,1)]
}
colnames(MA)[seq(44,50,1)] <- paste(c("material","lenght", "diameter",	"sharpened tip", "blunted tip", "monofilament",	"suture"))


## Location of perforation

# Writing csv for manual reconciliation:
write.csv(SA[,c(1,34)], file = "perforation_location_overview1.csv", row.names = F)

# Loading reconciled data:
perforation_location_reconciled_overview <- read.csv("perforation_location_reconciled_overview.csv")

# Adding them to MA
for (c in 1:nrow(MA)) {
  MA[c,seq(51,52,1)] <- perforation_location_reconciled_overview[perforation_location_reconciled_overview$StudyID == MA[c,1],seq(4,5,1)]
}
colnames(MA)[seq(51,52,1)] <- paste(c("location_perforation","side_location_perforation"))


## Mice age

# Writing csv for manual reconciliation:
write.csv(SA[,c(1,35)], file = "mice_age_overview1.csv", row.names = F)

# Loading reconciled data:
mice_age_reconciled_overview <- read.csv("mice_age_reconciled_overview.csv")

# Adding them to MA
for (c in 1:nrow(MA)) {
  MA[c,seq(53,54,1)] <- mice_age_reconciled_overview[mice_age_reconciled_overview$StudyID == MA[c,1],seq(4,5,1)]
}
colnames(MA)[seq(53,54,1)] <- paste(c("age_median","age_plus_minus"))


## Mice weight

# Writing csv for manual reconciliation:
write.csv(SA[,c(1,41)], file = "mice_weight_overview1.csv", row.names = F)

# Loading reconciled data:
mice_weight_reconciled_overview <- read.csv("mice_weight_reconciled_overview.csv")

# Adding them to MA
for (c in 1:nrow(MA)) {
  MA[c,seq(55,56,1)] <- mice_weight_reconciled_overview[mice_weight_reconciled_overview$StudyID == MA[c,1],seq(4,5,1)]
}
colnames(MA)[seq(55,56,1)] <- paste(c("weight_median","weight_plus_minus"))


## Duration of SAH perforation surgery

# As there are only two articles with reported surgery duration they get manually added:
MA[MA$StudyIdStr == "11660f81-c343-4396-a097-74ca3430d6fa", 57] <- 30
MA[MA$StudyIdStr == "6e8bdf4f-1be9-475c-8883-4bbbb6310b66", 57] <- 15
colnames(MA)[57] <- paste("surgery_duration")


## Detailed postsurgical stress/pain-mangement

# Writing csv for manual reconciliation:
write.csv(SA[,c(1,49)], file = "detailed_postsurgical_treatment_overview1.csv", row.names = F)

# Loading reconciled data:
postsurgical_treatment_reconciled_overview <- read.csv("postsurgical_treatment_reconciled_overview.csv")

# Adding them to MA
for (c in 1:nrow(MA)) {
  MA[c,58] <- postsurgical_treatment_reconciled_overview[postsurgical_treatment_reconciled_overview$StudyID == MA[c,1],5]
}
colnames(MA)[(58)] <- paste("subtance_postsurgical_treatment")


## Filament entry point

# Writing csv for manual reconciliation:
write.csv(SA[,c(1,56)], file = "entry_perforation1.csv", row.names = F)

# Loading reconciled data:
perforation_entry_reconciled_overview <- read.csv("perforation_entry_reconciled_overview.csv")

# Adding them to MA
for (c in 1:nrow(MA)) {
  MA[c,seq(59,60,1)] <- perforation_entry_reconciled_overview[perforation_entry_reconciled_overview$StudyID == MA[c,1],seq(4,5,1)]
}
colnames(MA)[seq(59,60,1)] <- paste(c("vessel_entry_perforation","side_entry_perforation"))





##### Preparation for Meta-analysis: one row per study

### Mortality:

# Way of calculation: Every experiments mortality data (deaths, number of animals) of an article will be summarized.


## For SAH animals

# Filtering mortality data ("mortality meta-analysis perforation"):
MMAP <- MA %>% filter(Which.type.of.outcome.was.assessed. == "Mortality rate (%)", ModelLabel == "SAH")

# Adding a column with joined StudyID and Experiment:
MMAP$joined_StudyID_Exp <- paste(MMAP$StudyIdStr, MMAP$Experiment)

# How many articles have multiple experiments?
MMAP %>% distinct(joined_StudyID_Exp, .keep_all = T) %>% select(1) %>% count() %>% filter(freq > 1)

# How many experiments have multiple data?
MMAP %>% select(joined_StudyID_Exp) %>% count() %>% filter(freq > 1)


## Idea: Rules for which data we take if there are multiple presented for an experiment
# A) If data are given for different times and for the same number of animals, take longest observational time
# B.1) If data are given for different times and for different numbers of animals, take the longest observational time, unless the corresponding number of animals is less than half of the highest number of animals. In this case, take the longest observational time of the highest number of animals (unless it's t < 1 d). 
# B.2) In addition, if the highest number of animals is corresponding to multiple times, take the longest observational time
# Maybe afterwards sensitivity analysis with opposite rules

# Creating a CSV with the experiments that have multiple data:
MMAP_exp_multiple_data <- MMAP %>% select(joined_StudyID_Exp) %>% count() %>% filter(freq > 1)
MMAP %>% filter(is.element(joined_StudyID_Exp, MMAP_exp_multiple_data$joined_StudyID_Exp)) %>% select(joined_StudyID_Exp, NumberOfAnimals, Time, Average) %>% write.csv("MMAP_exp_multiple_data1.csv", row.names = F)

# Loading the reconciled data:
MMAP_exp_multiple_data_reconciled <- read.csv("MMAP_exp_multiple_data_reconciled.csv")

# Filtering the reconciled data:
MMAP_exp_multiple_data_reconciled <- MMAP_exp_multiple_data_reconciled %>% filter(Reconciled == "x")

# Adding the reconciled "one row" data to MMAP while creating a new dataframe ("MMAP one row experiments"):
MMAP1RE <- MMAP %>% distinct(joined_StudyID_Exp, .keep_all = T)
for (e in 1:nrow(MMAP1RE)) {
  MMAP1RE[e,"NumberOfAnimals"] <- ifelse(is.element(MMAP1RE[e,"joined_StudyID_Exp"], MMAP_exp_multiple_data_reconciled$joined_StudyID_Exp),
                                         MMAP_exp_multiple_data_reconciled[MMAP_exp_multiple_data_reconciled$joined_StudyID_Exp == MMAP1RE[e,"joined_StudyID_Exp"],"NumberOfAnimals"],
                                         MMAP1RE[e, "NumberOfAnimals"])
}
for (e in 1:nrow(MMAP1RE)) {
  MMAP1RE[e,"Time"] <- ifelse(is.element(MMAP1RE[e,"joined_StudyID_Exp"], MMAP_exp_multiple_data_reconciled$joined_StudyID_Exp),
                              MMAP_exp_multiple_data_reconciled[MMAP_exp_multiple_data_reconciled$joined_StudyID_Exp == MMAP1RE[e,"joined_StudyID_Exp"],"Time"],
                              MMAP1RE[e, "Time"])
}
for (e in 1:nrow(MMAP1RE)) {
  MMAP1RE[e,"Average"] <- ifelse(is.element(MMAP1RE[e,"joined_StudyID_Exp"], MMAP_exp_multiple_data_reconciled$joined_StudyID_Exp),
                                 MMAP_exp_multiple_data_reconciled[MMAP_exp_multiple_data_reconciled$joined_StudyID_Exp == MMAP1RE[e,"joined_StudyID_Exp"],"Average"],
                                 MMAP1RE[e, "Average"])
}

# Creating a CSV with the articles that have multiple experiments:
MMAP_multiple_exp <- MMAP %>% distinct(joined_StudyID_Exp, .keep_all = T) %>% select(1) %>% count() %>% filter(freq > 1)
MMAP1RE %>% filter(is.element(StudyIdStr, MMAP_multiple_exp$StudyIdStr)) %>% select(StudyIdStr, Experiment, NumberOfAnimals, Time, Average) %>% write.csv("MMAP_exp_multiple_exp1.csv", row.names = F)

# Manually summarizing death and animal numbers of the experiments of an article (if different times were present, the longest was taken)
# Loading the reconciled data:
MMAP_exp_multiple_exp_reconciled <- read.csv("MMAP_exp_multiple_exp_reconciled.csv")

# Filtering reconciled data:
MMAP_exp_multiple_exp_reconciled <- MMAP_exp_multiple_exp_reconciled %>% filter(Experiment == "combined")

# Adding the reconciled studies to all articles:
MMAP1R <- MMAP1RE %>% distinct(StudyIdStr, .keep_all = T)
for (f in 1:nrow(MMAP1R)) {
  MMAP1R[f,"NumberOfAnimals"] <- ifelse(is.element(MMAP1R[f, "StudyIdStr"], MMAP_exp_multiple_exp_reconciled$StudyIdStr),
                                        MMAP_exp_multiple_exp_reconciled[MMAP_exp_multiple_exp_reconciled$StudyIdStr == MMAP1R[f, "StudyIdStr"],"NumberOfAnimals"],
                                        MMAP1R[f, "NumberOfAnimals"])
}
for (f in 1:nrow(MMAP1R)) {
  MMAP1R[f,"Time"] <- ifelse(is.element(MMAP1R[f, "StudyIdStr"], MMAP_exp_multiple_exp_reconciled$StudyIdStr),
                             MMAP_exp_multiple_exp_reconciled[MMAP_exp_multiple_exp_reconciled$StudyIdStr == MMAP1R[f, "StudyIdStr"],"Time"],
                             MMAP1R[f, "Time"])
}
for (f in 1:nrow(MMAP1R)) {
  MMAP1R[f,"Average"] <- ifelse(is.element(MMAP1R[f, "StudyIdStr"], MMAP_exp_multiple_exp_reconciled$StudyIdStr),
                                MMAP_exp_multiple_exp_reconciled[MMAP_exp_multiple_exp_reconciled$StudyIdStr == MMAP1R[f, "StudyIdStr"],"Average"],
                                MMAP1R[f, "Average"])
}


## Updating mortality information of articles that used both vehicle and no vehicle mice in an experiment:

# Article "2ea6da77-9ff3-41a6-9ad5-a46de336416b":
MMAP1R[MMAP1R$StudyIdStr == "2ea6da77-9ff3-41a6-9ad5-a46de336416b", "NumberOfAnimals"] <- 36
MMAP1R[MMAP1R$StudyIdStr == "2ea6da77-9ff3-41a6-9ad5-a46de336416b", "Average"] <- 11.111111

# Article "7e7d3286-31d1-4376-8373-8445a381b577": affects only SAH grade

# Article: "d9b32b94-334f-4bf7-bf75-2b74b39c4d75":
MMAP1R[MMAP1R$StudyIdStr == "d9b32b94-334f-4bf7-bf75-2b74b39c4d75", "NumberOfAnimals"] <- 67
MMAP1R[MMAP1R$StudyIdStr == "d9b32b94-334f-4bf7-bf75-2b74b39c4d75", "Average"] <- (23.076923*52+20*15)/(67)


## Adding a column with number of deaths:
MMAP1R$Deaths <- round(MMAP1R$NumberOfAnimals * MMAP1R$Average / 100, 0)
# Interestingly, for some articles, there are discrepancies between the mortality rate and number of animals not leading to integer numbers of death animals.


## For SHAM animals:

# Filtering mortality data ("mortality meta-analysis sham"):
MMAS <- MA %>% filter(Which.type.of.outcome.was.assessed. == "Mortality rate (%)", ModelLabel == "SHAM")

# Adding a column with joined StudyID and Experiment:
MMAS$joined_StudyID_Exp <- paste(MMAS$StudyIdStr, MMAS$Experiment)

# How many articles have multiple experiments?
MMAS %>% distinct(joined_StudyID_Exp, .keep_all = T) %>% select(1) %>% count() %>% filter(freq > 1)

# How many experiments have multiple data?
MMAS %>% select(joined_StudyID_Exp) %>% count() %>% filter(freq > 1)

# The same rules apply as for SAH mice above.

# Creating a CSV with the experiments that have multiple data:
MMAS_exp_multiple_data <- MMAS %>% select(joined_StudyID_Exp) %>% count() %>% filter(freq > 1)
MMAS %>% filter(is.element(joined_StudyID_Exp, MMAS_exp_multiple_data$joined_StudyID_Exp)) %>% select(joined_StudyID_Exp, NumberOfAnimals, Time, Average) %>% write.csv("MMAS_exp_multiple_data1.csv", row.names = F)

# Loading the reconciled data:
MMAS_exp_multiple_data_reconciled <- read.csv("MMAS_exp_multiple_data_reconciled.csv")

# Filtering the reconciled data:
MMAS_exp_multiple_data_reconciled <- MMAS_exp_multiple_data_reconciled %>% filter(Reconciled == "x")

# Adding the reconciled "one row" data to MMAS while creating a new dataframe ("MMAS one row experiments"):
MMAS1RE <- MMAS %>% distinct(joined_StudyID_Exp, .keep_all = T)
for (i in 1:nrow(MMAS1RE)) {
  MMAS1RE[i,"NumberOfAnimals"] <- ifelse(is.element(MMAS1RE[i,"joined_StudyID_Exp"], MMAS_exp_multiple_data_reconciled$joined_StudyID_Exp),
                                         MMAS_exp_multiple_data_reconciled[MMAS_exp_multiple_data_reconciled$joined_StudyID_Exp == MMAS1RE[i,"joined_StudyID_Exp"],"NumberOfAnimals"],
                                         MMAS1RE[i, "NumberOfAnimals"])
}
for (i in 1:nrow(MMAS1RE)) {
  MMAS1RE[i,"Time"] <- ifelse(is.element(MMAS1RE[i,"joined_StudyID_Exp"], MMAS_exp_multiple_data_reconciled$joined_StudyID_Exp),
                              MMAS_exp_multiple_data_reconciled[MMAS_exp_multiple_data_reconciled$joined_StudyID_Exp == MMAS1RE[i,"joined_StudyID_Exp"],"Time"],
                              MMAS1RE[i, "Time"])
}
for (i in 1:nrow(MMAS1RE)) {
  MMAS1RE[i,"Average"] <- ifelse(is.element(MMAS1RE[i,"joined_StudyID_Exp"], MMAS_exp_multiple_data_reconciled$joined_StudyID_Exp),
                                 MMAS_exp_multiple_data_reconciled[MMAS_exp_multiple_data_reconciled$joined_StudyID_Exp == MMAS1RE[i,"joined_StudyID_Exp"],"Average"],
                                 MMAS1RE[i, "Average"])
}

# Creating a CSV with the articles that have multiple experiments:
MMAS_multiple_exp <- MMAS %>% distinct(joined_StudyID_Exp, .keep_all = T) %>% select(StudyIdStr) %>% count() %>% filter(freq > 1)
MMAS1RE %>% filter(is.element(StudyIdStr, MMAS_multiple_exp$StudyIdStr)) %>% select(StudyIdStr, Experiment, NumberOfAnimals, Time, Average) %>% write.csv("MMAS_exp_multiple_exp1.csv", row.names = F)

# Manually summarizing death and animal numbers of the experiments of an article (if different times were present, the longest was taken)
# Loading the reconciled data:
MMAS_exp_multiple_exp_reconciled <- read.csv("MMAS_exp_multiple_exp_reconciled.csv")

# Filtering reconciled data:
MMAS_exp_multiple_exp_reconciled <- MMAS_exp_multiple_exp_reconciled %>% filter(Experiment == "combined")

# Adding the reconciled studies to all articles:
MMAS1R <- MMAS1RE %>% distinct(StudyIdStr, .keep_all = T)
for (j in 1:nrow(MMAS1R)) {
  MMAS1R[j,"NumberOfAnimals"] <- ifelse(is.element(MMAS1R[j, "StudyIdStr"], MMAS_exp_multiple_exp_reconciled$StudyIdStr),
                                        MMAS_exp_multiple_exp_reconciled[MMAS_exp_multiple_exp_reconciled$StudyIdStr == MMAS1R[j, "StudyIdStr"],"NumberOfAnimals"],
                                        MMAS1R[j, "NumberOfAnimals"])
}
for (j in 1:nrow(MMAS1R)) {
  MMAS1R[j,"Time"] <- ifelse(is.element(MMAS1R[j, "StudyIdStr"], MMAS_exp_multiple_exp_reconciled$StudyIdStr),
                             MMAS_exp_multiple_exp_reconciled[MMAS_exp_multiple_exp_reconciled$StudyIdStr == MMAS1R[j, "StudyIdStr"],"Time"],
                             MMAS1R[j, "Time"])
}
for (j in 1:nrow(MMAS1R)) {
  MMAS1R[j,"Average"] <- ifelse(is.element(MMAS1R[j, "StudyIdStr"], MMAS_exp_multiple_exp_reconciled$StudyIdStr),
                                MMAS_exp_multiple_exp_reconciled[MMAS_exp_multiple_exp_reconciled$StudyIdStr == MMAS1R[j, "StudyIdStr"],"Average"],
                                MMAS1R[j, "Average"])
}


## Adding a column with number of deaths:
MMAS1R$Deaths <- round(MMAS1R$NumberOfAnimals * MMAS1R$Average / 100, 0)



### SAH severity grade:

# Way of calculation: Every experiments mortality data (deaths, number of animals) of an article will be summarized.


## For SAH animals:

# Filtering mortality data ("grade meta-analysis perforation"):
GMAP <- MA %>% filter(Which.type.of.outcome.was.assessed. == "SAH grade", ModelLabel == "SAH")

# Adding a column with joined StudyID and Experiment:
GMAP$joined_StudyID_Exp <- paste(GMAP$StudyIdStr, GMAP$Experiment)

# How many articles have multiple experiments?
GMAP %>% distinct(joined_StudyID_Exp, .keep_all = T) %>% select(1) %>% count() %>% filter(freq > 1)

# How many experiments have multiple data?
GMAP %>% select(joined_StudyID_Exp) %>% count() %>% filter(freq > 1)

## Idea: Rules for which data we take if there are multiple presented for an experiment
# A) If data are given for different times and for the same number of animals, take longest observational time
# B.1) If data are given for different times and for different numbers of animals, take the longest observational time, unless the corresponding number of animals is less than half of the highest number of animals. In this case, take the longest observational time of the highest number of animals (unless it's t < 1 d). 
# B.2) In addition, if the highest number of animals is corresponding to multiple times, take the longest observational time
# Maybe afterwards sensitivity analysis with opposite rules

# Creating a CSV with the experiments that have multiple data:
GMAP_exp_multiple_data <- GMAP %>% select(joined_StudyID_Exp) %>% count() %>% filter(freq > 1)
GMAP %>% filter(is.element(joined_StudyID_Exp, GMAP_exp_multiple_data$joined_StudyID_Exp)) %>% select(joined_StudyID_Exp, NumberOfAnimals, Time, Average, Vehicle.control.) %>% write.csv("GMAP_exp_multiple_data1.csv", row.names = F)

# Loading the reconciled data:
GMAP_exp_multiple_data_reconciled <- read.csv("GMAP_exp_multiple_data_reconciled.csv")

# Filtering the reconciled data:
GMAP_exp_multiple_data_reconciled <- GMAP_exp_multiple_data_reconciled %>% filter(Reconciled == "x")

# Adding the reconciled "one row" data to GMAP while creating a new dataframe ("GMAP one row experiments"):
GMAP1RE <- GMAP %>% distinct(joined_StudyID_Exp, .keep_all = T)
for (k in 1:nrow(GMAP1RE)) {
  GMAP1RE[k,"NumberOfAnimals"] <- ifelse(is.element(GMAP1RE[k,"joined_StudyID_Exp"], GMAP_exp_multiple_data_reconciled$joined_StudyID_Exp),
                                         GMAP_exp_multiple_data_reconciled[GMAP_exp_multiple_data_reconciled$joined_StudyID_Exp == GMAP1RE[k,"joined_StudyID_Exp"],"NumberOfAnimals"],
                                         GMAP1RE[k, "NumberOfAnimals"])
}
for (k in 1:nrow(GMAP1RE)) {
  GMAP1RE[k,"Average"] <- ifelse(is.element(GMAP1RE[k,"joined_StudyID_Exp"], GMAP_exp_multiple_data_reconciled$joined_StudyID_Exp),
                                 GMAP_exp_multiple_data_reconciled[GMAP_exp_multiple_data_reconciled$joined_StudyID_Exp == GMAP1RE[k,"joined_StudyID_Exp"],"Average"],
                                 GMAP1RE[k, "Average"])
}
for (k in 1:nrow(GMAP1RE)) {
  GMAP1RE[k,"Time"] <- ifelse(is.element(GMAP1RE[k,"joined_StudyID_Exp"], GMAP_exp_multiple_data_reconciled$joined_StudyID_Exp),
                              GMAP_exp_multiple_data_reconciled[GMAP_exp_multiple_data_reconciled$joined_StudyID_Exp == GMAP1RE[k,"joined_StudyID_Exp"],"Time"],
                              GMAP1RE[k, "Time"])
}

# Creating a CSV with the articles that have multiple experiments:
GMAP_multiple_exp <- GMAP %>% distinct(joined_StudyID_Exp, .keep_all = T) %>% select(1) %>% count() %>% filter(freq > 1)
GMAP1RE %>% filter(is.element(StudyIdStr, GMAP_multiple_exp$StudyIdStr)) %>% select(StudyIdStr, Experiment, NumberOfAnimals, Time, Average, Vehicle.control.) %>% write.csv("GMAP_exp_multiple_exp1.csv", row.names = F)

# Manually summarizing SAH grades of the experiments of an article (weighted averages)
# Loading the reconciled data:
GMAP_exp_multiple_exp_reconciled <- read.csv("GMAP_exp_multiple_exp_reconciled.csv")

# Filtering reconciled data:
GMAP_exp_multiple_exp_reconciled <- GMAP_exp_multiple_exp_reconciled %>% filter(Experiment == "combined")

# Adding the reconciled studies to all articles:
GMAP1R <- GMAP1RE %>% distinct(StudyIdStr, .keep_all = T)
for (l in 1:nrow(GMAP1R)) {
  GMAP1R[l,"NumberOfAnimals"] <- ifelse(is.element(GMAP1R[l, "StudyIdStr"], GMAP_exp_multiple_exp_reconciled$StudyIdStr),
                                        GMAP_exp_multiple_exp_reconciled[GMAP_exp_multiple_exp_reconciled$StudyIdStr == GMAP1R[l, "StudyIdStr"],"NumberOfAnimals"],
                                        GMAP1R[l, "NumberOfAnimals"])
}
for (l in 1:nrow(GMAP1R)) {
  GMAP1R[l,"Time"] <- ifelse(is.element(GMAP1R[l, "StudyIdStr"], GMAP_exp_multiple_exp_reconciled$StudyIdStr),
                             GMAP_exp_multiple_exp_reconciled[GMAP_exp_multiple_exp_reconciled$StudyIdStr == GMAP1R[l, "StudyIdStr"],"Time"],
                             GMAP1R[l, "Time"])
}
for (l in 1:nrow(GMAP1R)) {
  GMAP1R[l,"Average"] <- ifelse(is.element(GMAP1R[l, "StudyIdStr"], GMAP_exp_multiple_exp_reconciled$StudyIdStr),
                                GMAP_exp_multiple_exp_reconciled[GMAP_exp_multiple_exp_reconciled$StudyIdStr == GMAP1R[l, "StudyIdStr"],"Average"],
                                GMAP1R[l, "Average"])
}

# Filtering for grading system described by Sugawara (2008):
GMAP1R <- GMAP1R %>% filter(Reconciled.SAH.grading.system == "Sugawara et al. 2008")
# Three articles got excluded. 


## For SHAM animals:

# Filtering mortality data ("grade meta-analysis sham"):
GMAS <- MA %>% filter(Which.type.of.outcome.was.assessed. == "SAH grade", ModelLabel == "SHAM")

# As almost every SAH severity grade was 0, a meta-analysis does not seem to be reasonable.
# Instead, descriptive statistics are used.



### Vasospasm:

# Effect size = Artery diameter of SAH mice / Artery diameter of the corresponding sham-operated mice

# Filtering vasospasm data ("vasospasm meta-analysis perforation"):
VMAP <- MA %>% filter(Which.type.of.outcome.was.assessed. != "SAH grade") %>% filter(Which.type.of.outcome.was.assessed. != "Mortality rate (%)") %>% filter(ModelLabel == "SAH")


## Getting the corresponding sham-operated mice diameters:

# Adding a column with joined StudyID, Experiment, Time, Vessel, Vehicle:
VMAP$joined_Info <- paste(VMAP$StudyIdStr, VMAP$Experiment, VMAP$Time, VMAP$Which.type.of.outcome.was.assessed., VMAP$Vehicle.control.)

# Are these info unique?:
VMAP %>% select(joined_Info) %>% unique() %>% nrow() == nrow(VMAP)

# Filtering SHAM vasospasm data ("vasospasm meta-analysis SHAM"):
VMAS <- MA %>% filter(Which.type.of.outcome.was.assessed. != "SAH grade") %>% filter(Which.type.of.outcome.was.assessed. != "Mortality rate (%)") %>% filter(ModelLabel == "SHAM")

# Adding a column with joined StudyID, Experiment, Time, Vessel, Vehicle:
VMAS$joined_Info <- paste(VMAS$StudyIdStr, VMAS$Experiment, VMAS$Time, VMAS$Which.type.of.outcome.was.assessed., VMAS$Vehicle.control.)

# Are these info unique?:
VMAS %>% select(joined_Info) %>% unique() %>% nrow() == nrow(VMAS)

# Which SAH data have no corresponding SHAM data?:
VMAP %>% filter(!is.element(joined_Info, VMAS$joined_Info))

# This one data has to be excluded from further analysis.
VMAP <- VMAP %>% filter(is.element(joined_Info, VMAS$joined_Info))

# Adding the corresponding sham values:
for (n in 1:nrow(VMAP)) {
  VMAP[n,"Average_SHAM"] <- VMAS %>% filter(joined_Info == VMAP[n,"joined_Info"]) %>% select(Average)
}
for (n in 1:nrow(VMAP)) {
  VMAP[n,"Error_SHAM"] <- VMAS %>% filter(joined_Info == VMAP[n,"joined_Info"]) %>% select(Error)
}
for (n in 1:nrow(VMAP)) {
  VMAP[n,"NumberMice_SHAM"] <- VMAS %>% filter(joined_Info == VMAP[n,"joined_Info"]) %>% select(NumberOfAnimals)
}

# Adding a column with the ratio of SAH arteries diameter to SHAM arteries diameter:
VMAP$ratio_SAH_arteries <- VMAP$Average / VMAP$Average_SHAM

# Adding a column with the SD of SAH arteries diameter in comparison to SHAM arteries diameter:
VMAP$Error <- as.numeric(VMAP$Error)
VMAP$SD <- ifelse(VMAP$ErrorType == "SEM", VMAP$Error * sqrt(VMAP$NumberOfAnimals), VMAP$Error)
VMAP$SHAM_relative_SD <- VMAP$SD / VMAP$Average_SHAM
VMAP$SHAM_relative_Variance <- VMAP$SHAM_relative_SD^2


## Articles mean vasospasm (and SD & variance):

# Article: d4d7776b-93ce-43d4-a9b4-4278088aa35f:
VMAP %>% filter(StudyIdStr == "d4d7776b-93ce-43d4-a9b4-4278088aa35f") %>% select(ratio_SAH_arteries) %>% unlist() %>% mean()
VMAP %>% filter(StudyIdStr == "d4d7776b-93ce-43d4-a9b4-4278088aa35f") %>% select(SHAM_relative_SD) %>% unlist() %>% mean()
VMAP %>% filter(StudyIdStr == "d4d7776b-93ce-43d4-a9b4-4278088aa35f") %>% select(SHAM_relative_Variance) %>% unlist() %>% mean()

# Article: f0846ef5-5cfe-4481-a655-5b3b63d47e49:
VMAP %>% filter(StudyIdStr == "f0846ef5-5cfe-4481-a655-5b3b63d47e49") %>% select(ratio_SAH_arteries) %>% unlist() %>% mean()
VMAP %>% filter(StudyIdStr == "f0846ef5-5cfe-4481-a655-5b3b63d47e49") %>% select(SHAM_relative_SD) %>% unlist() %>% mean()
VMAP %>% filter(StudyIdStr == "f0846ef5-5cfe-4481-a655-5b3b63d47e49") %>% select(SHAM_relative_Variance) %>% unlist() %>% mean()

# The three remaining article only have one row, so no summarization needed there.
# One article got excluded from analysis as it did not report the number of animals: 4e20f054-08ef-4296-994e-6ca213e76698 


## Mean of the articles mean vasospasm:

# Articles variances:
var1 <- 0.048380849
var2 <- 0.037902142
var3 <- 0.057478928
var4 <- VMAP %>% filter(StudyIdStr == "d4d7776b-93ce-43d4-a9b4-4278088aa35f") %>% select(SHAM_relative_Variance) %>% unlist() %>% mean()
var5 <- VMAP %>% filter(StudyIdStr == "f0846ef5-5cfe-4481-a655-5b3b63d47e49") %>% select(SHAM_relative_Variance) %>% unlist() %>% mean()

# Creating a dataframe with these data:
vasospasm_mean <- data.frame(Mean = c(0.6956067, 0.7422460, 0.7339642, 0.4990354, 0.9043201), Variance = c(var1, var2, var3, var4, var5))
vasospasm_mean$StudyID <- VMAP %>% select(StudyIdStr) %>% unique()
vasospasm_mean$n <- c(17,15,16,7,9)
vasospasm_mean$SD <- sqrt(vasospasm_mean$Variance)

# Common mean:
vasospasm_mean$n_times_mean <- vasospasm_mean$Mean * vasospasm_mean$n
sum(vasospasm_mean$n_times_mean) / sum(vasospasm_mean$n)
# The common vasospasm mean is 0.7239775.

# Common variance:
vasospasm_mean$sum_of_squares <- vasospasm_mean$n * (vasospasm_mean$Mean^2 + vasospasm_mean$Variance)
(sum(vasospasm_mean$sum_of_squares) / sum(vasospasm_mean$n)) - (sum(vasospasm_mean$n_times_mean) / sum(vasospasm_mean$n))^2
# The common vasospasm variance is 0.0497293.

# Common standard deviation:
sqrt((sum(vasospasm_mean$sum_of_squares) / sum(vasospasm_mean$n)) - (sum(vasospasm_mean$n_times_mean) / sum(vasospasm_mean$n))^2)
# The common vasospasm standard deviation is 0.2230007.

# Common confidence interval
(sum(vasospasm_mean$n_times_mean) / sum(vasospasm_mean$n)) - 1.96 * (sqrt((sum(vasospasm_mean$sum_of_squares) / sum(vasospasm_mean$n)) - (sum(vasospasm_mean$n_times_mean) / sum(vasospasm_mean$n))^2))
(sum(vasospasm_mean$n_times_mean) / sum(vasospasm_mean$n)) + 1.96 * (sqrt((sum(vasospasm_mean$sum_of_squares) / sum(vasospasm_mean$n)) - (sum(vasospasm_mean$n_times_mean) / sum(vasospasm_mean$n))^2))


## Getting perforations sides:

SA %>% filter(StudyIdStr == "1a12d870-e9b4-43c4-af98-a3f1b5caad5e") %>% select(feef2370.3b71.4e0c.9724.8c0c3eba7970_Where.was.the.perforation.entry.point., X7cf59b31.bba7.4207.8ff5.750bec9bfd9c_Where.was.the.location.of.perforation.)
SA %>% filter(StudyIdStr == "85471734-be40-44d0-b54e-216a1aeb6214") %>% select(feef2370.3b71.4e0c.9724.8c0c3eba7970_Where.was.the.perforation.entry.point., X7cf59b31.bba7.4207.8ff5.750bec9bfd9c_Where.was.the.location.of.perforation.)
SA %>% filter(StudyIdStr == "aadfb399-9468-4126-8bac-95f20fb9bf16") %>% select(feef2370.3b71.4e0c.9724.8c0c3eba7970_Where.was.the.perforation.entry.point., X7cf59b31.bba7.4207.8ff5.750bec9bfd9c_Where.was.the.location.of.perforation.)
SA %>% filter(StudyIdStr == "d4d7776b-93ce-43d4-a9b4-4278088aa35f") %>% select(feef2370.3b71.4e0c.9724.8c0c3eba7970_Where.was.the.perforation.entry.point., X7cf59b31.bba7.4207.8ff5.750bec9bfd9c_Where.was.the.location.of.perforation.)
SA %>% filter(StudyIdStr == "f0846ef5-5cfe-4481-a655-5b3b63d47e49") %>% select(feef2370.3b71.4e0c.9724.8c0c3eba7970_Where.was.the.perforation.entry.point., X7cf59b31.bba7.4207.8ff5.750bec9bfd9c_Where.was.the.location.of.perforation.)





##### Meta-analysis of mortality

#### SAH perforation mice

### Without moderators (one row per article)

# Calculating effect sizes (proportions of dead animals):
MMAP1R <- escalc(xi = Deaths, ni = NumberOfAnimals, measure = "PLO", data = MMAP1R)

# Running Meta-analysis
MMAP1RwoMods <- rma(yi, vi, method = "DL", level = 95, data = MMAP1R)
MMAP1RwoMods
confint(MMAP1RwoMods)
predict(MMAP1RwoMods, transf=transf.ilogit)


## Forest plot:

# Preparations (authors and years of the articles):
SAH_Articles_studyIDs_authors <- read.csv("SAH_Articles_studyIDs_authors.csv")
SAH_Articles_studyIDs_authors$first_author <- word(SAH_Articles_studyIDs_authors$Authors, 1)
SAH_Articles_studyIDs_authors$first_author_year <- paste(SAH_Articles_studyIDs_authors$first_author," (",SAH_Articles_studyIDs_authors$Year,")", sep = "")

# Creating a CSV for adding missing authors of the articles that are in MMAP1R:
SAH_Articles_studyIDs_authors %>% filter(is.element(SAH_Articles_studyIDs_authors$idStr, MMAP1R$StudyIdStr)) %>% write.csv("SAH_Articles_studyIDs_authors_missing_MMAP.csv", row.names = F)

# Loading the added authors:
SAH_Articles_studyIDs_authors <- read.csv("SAH_Articles_studyIDs_authors_missing_MMAP_reconciled.csv")
SAH_Articles_studyIDs_authors$first_author <- word(SAH_Articles_studyIDs_authors$Authors, 1)
SAH_Articles_studyIDs_authors$first_author_year <- paste(SAH_Articles_studyIDs_authors$first_author," (",SAH_Articles_studyIDs_authors$Year,")", sep = "")

# Checking if every article of MMAP1R has author information:
SAH_Articles_studyIDs_authors %>% filter(is.element(SAH_Articles_studyIDs_authors$idStr, MMAP1R$StudyIdStr)) %>% select(first_author_year)

# There are two duplicate author and year descriptions: Egashira (2015) and Muroi (2014)
# It was manually checked that they are unique studies and not duplicates

# Adding the information to MMAP1R:
for (g in 1:nrow(MMAP1R)) {
  MMAP1R[g,65] <- SAH_Articles_studyIDs_authors %>% filter(idStr == MMAP1R[g,"StudyIdStr"]) %>% select(first_author_year)
}
colnames(MMAP1R)[65] <- paste("first_author_year")

# Changing column names of animals and deaths:
colnames(MMAP1R)[c(62,6)] <- paste(c("cases","total"))

# Drawing and saving forest plot:
pdf(file = "SAH_mortality_forest.pdf", width = 10, height = 15)

pesMMAP.summary=metaprop(cases, total, first_author_year, data=MMAP1R, sm="PLO")
forest(pesMMAP.summary,
       sortvar = TE,
       fixed = FALSE,
       xlab = "Mortality rate", ff.xlab = "bold",
       print.tau2.ci = T, print.I2.ci = T,
       digits = 3, digits.pval.Q = 3, digits.I2 = 1,
       fs.hetstat = 12,
       addrows = 3)

dev.off()



### Univariate Meta-regressions

## Twelve-hour light-dark cycle:

# Preparations:
MMAP1R$X12.hour.light.dark.cycle <- ifelse(MMAP1R$X12.hour.light.dark.cycle == "x", TRUE, FALSE)
MMAP1R$X12.hour.light.dark.cycle <- ifelse(is.na(MMAP1R$X12.hour.light.dark.cycle), FALSE, MMAP1R$X12.hour.light.dark.cycle)

# Meta-regression:
MMAP1R12hld <- rma(yi, vi, method = "DL", mods = ~factor(X12.hour.light.dark.cycle), level = 95, data = MMAP1R)
MMAP1R12hld


## Free access to food and water:

# Preparations:
MMAP1R$free.access.to.food.and.water <- ifelse(MMAP1R$free.access.to.food.and.water == "x", TRUE, FALSE)
MMAP1R$free.access.to.food.and.water <- ifelse(is.na(MMAP1R$free.access.to.food.and.water), FALSE, MMAP1R$free.access.to.food.and.water)

# Meta-regression:
MMAP1Rfood <- rma(yi, vi, method = "DL", mods = ~factor(free.access.to.food.and.water), level = 95, data = MMAP1R)
MMAP1Rfood 


## Controlled humidity: 

# Preparations:
MMAP1R$controlled.humidity <- ifelse(MMAP1R$controlled.humidity == "x", TRUE, FALSE)
MMAP1R$controlled.humidity <- ifelse(is.na(MMAP1R$controlled.humidity), FALSE, MMAP1R$controlled.humidity)

# Meta-regression:
MMAP1Rhumidity <- rma(yi, vi, method = "DL", mods = ~factor(controlled.humidity), level = 95, data = MMAP1R)
MMAP1Rhumidity 


## Controlled temperature:
MMAP1R$controlled.temperature <- ifelse(MMAP1R$controlled.temperature == "x", TRUE, FALSE)
MMAP1R$controlled.temperature <- ifelse(is.na(MMAP1R$controlled.temperature), FALSE, MMAP1R$controlled.temperature)

# Meta-regression:
MMAP1Rtemperature <- rma(yi, vi, method = "DL", mods = ~factor(controlled.temperature), level = 95, data = MMAP1R)
MMAP1Rtemperature 


## Type of anaesthesia

MMAP1RtypeAnaesthesia <- rma(yi, vi, method = "DL", mods = ~factor(type.of.anesthesia), level = 95, data = MMAP1R)
MMAP1RtypeAnaesthesia


## Injective anaesthesia drug

# Preparations:
MMAP1R$injetive_anesthetic_substance <- ifelse(is.na(MMAP1R$injetive_anesthetic_substance), "not reported", MMAP1R$injetive_anesthetic_substance)

# Filtering only articles with injective type of anaesthesia:
MMAP1R_injective_anaes <- MMAP1R %>% filter(type.of.anesthesia == "Injective")

# Meta-regression:
MMAP1RInjnaesthesiaDrug <- rma(yi, vi, method = "DL", mods = ~factor(injetive_anesthetic_substance), level = 95, data = MMAP1R_injective_anaes)
MMAP1RInjnaesthesiaDrug


## Intubation

MMAP1RIntubation <- rma(yi, vi, method = "DL", mods = ~factor(intubation), level = 95, data = MMAP1R)
MMAP1RIntubation


## Location of perforation

MMAP1RLocationPerforation <- rma(yi, vi, method = "DL", mods = ~factor(location_perforation), level = 95, data = MMAP1R)
MMAP1RLocationPerforation


## Monitoring of ICP

MMAP1RICP <- rma(yi, vi, method = "DL", mods = ~factor(ICP.monitoring), level = 95, data = MMAP1R)
MMAP1RICP


## Postoperative stress/pain-management

MMAP1RpostOPmanagement <- rma(yi, vi, method = "DL", mods = ~factor(postsurgical.treatment), level = 95, data = MMAP1R)
MMAP1RpostOPmanagement


## Filament diameter

MMAP1RfilamentDiameter <- rma(yi, vi, method = "DL", mods = ~factor(filament.size), level = 95, data = MMAP1R)
MMAP1RfilamentDiameter


## Filament material

MMAP1RFilamentMaterial <- rma(yi, vi, method = "DL", mods = ~factor(material), level = 95, data = MMAP1R)
MMAP1RFilamentMaterial


## Filament tip

# Preparations:
MMAP1R$blunted_sharpened <- ifelse(MMAP1R$sharpened.tip == "x","sharpened", 
                                   ifelse(MMAP1R$blunted.tip == "x", "blunted","not reported"))

# Meta-regression:
MMAP1RFilamentTip <- rma(yi, vi, method = "DL", mods = ~factor(blunted_sharpened), level = 95, data = MMAP1R)
MMAP1RFilamentTip


## Description of filament texture (Monofilament vs Suture)

# Preparations:
MMAP1R$filament_texture <- ifelse(MMAP1R$monofilament == "x" & MMAP1R$suture == "x", "both monofilament and suture",
                                  ifelse(MMAP1R$suture == "x", "suture",
                                         ifelse(MMAP1R$monofilament == "x", "monofilament", "neither monofilament or suture")))

# Meta-regression:
MMAP1RFilamentTexture <- rma(yi, vi, method = "DL", mods = ~factor(filament_texture), level = 95, data = MMAP1R)
MMAP1RFilamentTexture


## Vehicle control:

# Subgroup analysis would be useful (vehicle used vs. no vehicle used)!

# Data with vehicle control:
MA %>% filter(Vehicle.control. != "")

# Filtering experiments that used both vehicle and no vehicle control:
Studies_both_vehicle_novehicle <- MA %>% filter(Which.type.of.outcome.was.assessed. == "Mortality rate (%)") %>% filter(ModelLabel == "SAH") %>% distinct(StudyIdStr, Vehicle.control., .keep_all = T) %>% select(StudyIdStr) %>% count() %>% filter(freq > 1)

# Manually dividing these articles mortality data into vehicle and no vehicle:
MA %>% filter(is.element(StudyIdStr, Studies_both_vehicle_novehicle$StudyIdStr)) %>% filter(ModelLabel == "SAH") %>% filter(Which.type.of.outcome.was.assessed. == "Mortality rate (%)") %>% select(StudyIdStr, Experiment, NumberOfAnimals, Time, Average, Vehicle.control., ModelLabel, Which.type.of.outcome.was.assessed.) %>% write.csv("Studies_both_vehicle_novehicle.csv", row.names = F)

# MMAP1R for comparison:
write.csv(MMAP1R, file = "MMAP1R.csv", row.names = F)

# Loading manually vehicle divided data:
Studies_both_vehicle_novehicle_reconciled <- read.csv("Studies_both_vehicle_novehicle_reconciled.csv")
Studies_both_vehicle_novehicle_reconciled <- Studies_both_vehicle_novehicle_reconciled %>% filter(Experiment == "vehicle reconciliation")

# Which articles have solely used vehicle control?:
Studies_only_vehicle_or_novehicle <- MA %>% filter(Which.type.of.outcome.was.assessed. == "Mortality rate (%)") %>% filter(ModelLabel == "SAH") %>% distinct(StudyIdStr, Vehicle.control., .keep_all = T) %>% select(StudyIdStr) %>% count() %>% filter(freq == 1)
MMAP1R %>% filter(is.element(StudyIdStr, Studies_only_vehicle_or_novehicle$StudyIdStr)) %>% filter(Vehicle.control. != "") %>% select(StudyIdStr)

# Which articles have solely used no vehicle control?:
MMAP1R %>% filter(is.element(StudyIdStr, Studies_only_vehicle_or_novehicle$StudyIdStr)) %>% filter(Vehicle.control. == "") %>% select(StudyIdStr)

# Duplicate rows in MMAP1R of articles using both vehicle and no vehicle control:
MMAP1R_vehicle_divided <- rbind(MMAP1R, MMAP1R[is.element(MMAP1R$StudyIdStr, Studies_both_vehicle_novehicle_reconciled$StudyIdStr),])

# Adding a column with information whether vehicle or no vehicle was used:
MMAP1R_vehicle_divided[is.element(MMAP1R_vehicle_divided$StudyIdStr, Studies_both_vehicle_novehicle_reconciled$StudyIdStr),67] <- "no vehicle"
MMAP1R_vehicle_divided[41:46,67] <- "vehicle"
MMAP1R_vehicle_divided[!is.element(MMAP1R_vehicle_divided$StudyIdStr, Studies_both_vehicle_novehicle_reconciled$StudyIdStr),67] <- ifelse(
  MMAP1R_vehicle_divided[!is.element(MMAP1R_vehicle_divided$StudyIdStr, Studies_both_vehicle_novehicle_reconciled$StudyIdStr),"Vehicle.control."] != "", "vehicle", "no vehicle"
)
colnames(MMAP1R_vehicle_divided)[67] <- paste("vehicle_reconciled")  

# Removing one row as one article that used only vehicle ("61702aff-9b39-42fe-8c00-c62c2bff42ae"):
MMAP1R_vehicle_divided <- MMAP1R_vehicle_divided[-43,]

# Adding a column with joined StudyID and vehicle information:
MMAP1R_vehicle_divided$joined_StudyID_vehicle <- paste(MMAP1R_vehicle_divided$StudyIdStr, MMAP1R_vehicle_divided$vehicle_reconciled)
Studies_both_vehicle_novehicle_reconciled$joined_StudyID_vehicle <- paste(Studies_both_vehicle_novehicle_reconciled$StudyIdStr, Studies_both_vehicle_novehicle_reconciled$Vehicle_reconciled)

# Adding the animal number and death information from the vehicle reconciliation:
for (h in 1:nrow(MMAP1R_vehicle_divided)) {
  MMAP1R_vehicle_divided[h, "Time"] <- ifelse(is.element(MMAP1R_vehicle_divided[h, "joined_StudyID_vehicle"], Studies_both_vehicle_novehicle_reconciled$joined_StudyID_vehicle),
                                              Studies_both_vehicle_novehicle_reconciled[Studies_both_vehicle_novehicle_reconciled$joined_StudyID_vehicle == MMAP1R_vehicle_divided[h, "joined_StudyID_vehicle"], "Time"],
                                              MMAP1R_vehicle_divided[h, "Time"])
}
for (h in 1:nrow(MMAP1R_vehicle_divided)) {
  MMAP1R_vehicle_divided[h, "Average"] <- ifelse(is.element(MMAP1R_vehicle_divided[h, "joined_StudyID_vehicle"], Studies_both_vehicle_novehicle_reconciled$joined_StudyID_vehicle),
                                                 Studies_both_vehicle_novehicle_reconciled[Studies_both_vehicle_novehicle_reconciled$joined_StudyID_vehicle == MMAP1R_vehicle_divided[h, "joined_StudyID_vehicle"], "Average"],
                                                 MMAP1R_vehicle_divided[h, "Average"])
}
for (h in 1:nrow(MMAP1R_vehicle_divided)) {
  MMAP1R_vehicle_divided[h, "total"] <- ifelse(is.element(MMAP1R_vehicle_divided[h, "joined_StudyID_vehicle"], Studies_both_vehicle_novehicle_reconciled$joined_StudyID_vehicle),
                                               Studies_both_vehicle_novehicle_reconciled[Studies_both_vehicle_novehicle_reconciled$joined_StudyID_vehicle == MMAP1R_vehicle_divided[h, "joined_StudyID_vehicle"], "NumberOfAnimals"],
                                               MMAP1R_vehicle_divided[h, "total"])
}
colnames(MMAP1R_vehicle_divided)[6] <- paste("NumberOfAnimals")

# Rerun calculation of proportional effect sizes:
MMAP1R_vehicle_divided$Deaths <- round(MMAP1R_vehicle_divided$NumberOfAnimals * MMAP1R_vehicle_divided$Average / 100, 0)
MMAP1R_vehicle_divided <- escalc(xi = Deaths, ni = NumberOfAnimals, measure = "PLO", data = MMAP1R_vehicle_divided)

# Subgroup analysis (vehicle vs. no vehicle):
# Assumption: We do not assume a common between-study variance component (i.e., we do not pool within-group estimates of between-study variance)
MMAP1R_Vehicle <- rma(yi, vi, method = "DL", data = MMAP1R_vehicle_divided, subset = vehicle_reconciled == "vehicle")
MMAP1R_No_Vehicle <- rma(yi, vi, method = "DL", data = MMAP1R_vehicle_divided, subset = vehicle_reconciled == "no vehicle")
MMAP1R_Vehicle_predict <- predict(MMAP1R_Vehicle, transf = transf.ilogit)
MMAP1R_No_Vehicle_predict <- predict(MMAP1R_No_Vehicle, transf = transf.ilogit)
dat.diffvarVehicle <- data.frame(estimate = c(MMAP1R_Vehicle$b, MMAP1R_No_Vehicle$b),
                                 stderror = c(MMAP1R_Vehicle$se, MMAP1R_No_Vehicle$se),
                                 moderator = c("vehicle", "no vehicle"),
                                 tau2 = round(c(MMAP1R_Vehicle$tau2,
                                                MMAP1R_No_Vehicle$tau2), 3))
subganal.moderatorVehicle <- rma(estimate, sei=stderror, mods=~moderator, method="FE", data=dat.diffvarVehicle)
pes.moderatorVehicle <- rma(estimate, sei=stderror, method="FE", data=dat.diffvarVehicle)
pes.moderatorVehicle <- predict(pes.moderatorVehicle)
MMAP1R_Vehicle_predict
MMAP1R_No_Vehicle_predict
subganal.moderatorVehicle
pes.moderatorVehicle
# Mixed-effects model for subgroup analysis!
# Is appropriate according to Wang (2018, https://www.researchgate.net/publication/325486099_How_to_Conduct_a_Meta-Analysis_of_Proportions_in_R_A_Comprehensive_Tutorial): " On the other hand, if we believe that apart from sampling errors, some systematic causes are also responsible for the differential values of the observed within-group ??au^2, then we apply separate estimates of ??au^2 for each subgroup."


## Time

# We are using a three-level random-effects model for analysis of time dependency of mortality
# Thereby, Level three represents the articles and Level two all belonging mortalities at different timepoints after SAH to each article.

# Calculating effect sizes:
MMAP$deaths <- round(MMAP$Average * MMAP$NumberOfAnimals / 100, 0)
MMAP$rn <- row_number(MMAP$StudyIdStr)
MMAP <- escalc(xi = deaths, ni = NumberOfAnimals, measure = "PLO", data = MMAP)

# How many data have unreported times after SAH?:
MMAP %>% filter(is.na(Time)) %>% nrow()

# Converting time into numericals:
MMAP$Time <- as.numeric(MMAP$Time)

# Meta-regression (excluding unreported times after SAH):
MMAP3Ltime <- rma.mv(yi,vi, random = list(~ 1 | rn, ~ 1 | StudyIdStr), mods = ~Time ,method = "REML", data = MMAP)
MMAP3Ltime
transf.ilogit(-1.6093)
transf.ilogit(-1.6093+0.0623)
transf.ilogit(-1.6093+3*0.0623)
confint(MMAP3Ltime)
i2_ml(MMAP3Ltime)
r2_ml(MMAP3Ltime)
# CAVE: Note that REML method was used for tau^2 estimation as DL is not possible.



### Sensitivity analysis: Excluding hyperacute studies (t < 1 day):

MMAP1R$Time <- as.numeric(MMAP1R$Time)
MMAP1RwoHyperacute <- MMAP1R %>% filter(Time >= 1)

## No moderators:
MMAP1RwoHyperacuteWoMods <- rma(yi, vi, method = "DL", level = 95, data = MMAP1RwoHyperacute)
MMAP1RwoHyperacuteWoMods
predict(MMAP1RwoHyperacuteWoMods, transf = transf.ilogit)
confint(MMAP1RwoHyperacuteWoMods)


## Meta-regression with filament material:
MMAP1RwoHyperacuteMaterial <- rma(yi, vi, method = "DL", mods = ~factor(material), level = 95, data = MMAP1RwoHyperacute)
MMAP1RwoHyperacuteMaterial
confint(MMAP1RwoHyperacuteMaterial)
predict(MMAP1RwoHyperacuteMaterial, transf = transf.ilogit)

# Mean time after SAH per material type:
MMAP1RwoHyperacute %>% filter(material == "Nylon") %>% select(Time) %>% unlist() %>% mean()
MMAP1RwoHyperacute %>% filter(material == "Nylon") %>% select(Time) %>% unlist() %>% sd()
MMAP1RwoHyperacute %>% filter(material == "Prolene") %>% select(Time) %>% unlist() %>% mean()
MMAP1RwoHyperacute %>% filter(material == "Prolene") %>% select(Time) %>% unlist() %>% sd()
MMAP1RwoHyperacute %>% filter(material == "") %>% select(Time) %>% unlist() %>% mean()
MMAP1RwoHyperacute %>% filter(material == "") %>% select(Time) %>% unlist() %>% sd()




#### SHAM mice

### Without moderators (one row per article)

# Calculating effect sizes (proportions of dead animals):
MMAS1R <- escalc(xi = Deaths, ni = NumberOfAnimals, measure = "PLO", data = MMAS1R)

# Number of mice:
sum(MMAS1R$NumberOfAnimals)

# How many articles had zero mortality?
MMAS1R %>% filter(Deaths == 0) %>% nrow()

# What was the maximum mortality rate?
MMAS1R %>% select(Average) %>% max()

# Running Meta-analysis
MMAS1RwoMods <- rma(yi, vi, method = "DL", level = 95, data = MMAS1R)
MMAS1RwoMods
confint(MMAS1RwoMods)
predict(MMAS1RwoMods, transf=transf.ilogit)

# Plotting a forest plot seems not to be reasonable, as most of the articles reported zero mortality.
# Moreover, meta-regressions for mortality moderation investigation seems not to be reasonable as the test for heterogeneity showed no significance.





##### Meta-analysis of SAH grade

#### SAH perforation mice

### Without moderators (one row per article)

# Manually adding missing error types:
GMAP1R[GMAP1R$StudyIdStr == "cf210ee3-a04e-4036-a0d9-238e7caf7a06", "ErrorType"] <- "SD"
GMAP1R[GMAP1R$StudyIdStr == "ef4ad15c-3f9b-4efd-84a1-ab94609caceb", "ErrorType"] <- "SD"
GMAP1R[GMAP1R$StudyIdStr == "7faa52e0-6c96-4611-92ae-5e938b1af4f7", "ErrorType"] <- "SEM"
GMAP1R[GMAP1R$StudyIdStr == "55615754-99dc-4dba-a628-da3b780a3d99", "ErrorType"] <- "SD"

# Adding columns with the SD:
GMAP1R$Error <- as.numeric(GMAP1R$Error)
GMAP1R$SD <- ifelse(GMAP1R$ErrorType == "SEM", GMAP1R$Error * sqrt(GMAP1R$NumberOfAnimals), GMAP1R$Error)

# Adding authors and years of studies:
for (z in 1:nrow(GMAP1R)) {
  GMAP1R[z,63] <- SAH_Articles_studyIDs_authors %>% filter(idStr == GMAP1R[z,"StudyIdStr"]) %>% select(first_author_year)
}
colnames(GMAP1R)[63] <- paste("first_author_year")


## Meta-analysis (without moderators):
GMAP1R <- GMAP1R[order(GMAP1R$Average),]
GMAP1RwoMods <- rma(yi = Average, sei = SD, method = "DL", level = 95, data = GMAP1R)
GMAP1RwoMods
confint(GMAP1RwoMods)
predict(GMAP1RwoMods)


## Forest plot:

pesGMAP.summary <- metamean(mean = Average, sd = SD, n = rep(1,16), studlab = first_author_year, data=GMAP1R, level = 0.95, method.tau = "DL", sm = "MRAW", method.ci = "z")
pesGMAP.summary

pdf(file = "SAH severity score forest WRONG TOTALS.pdf", width = 10, height = 7.5)

forest(pesGMAP.summary,
       fixed = FALSE,
       xlab = "SAH severity score", ff.xlab = "bold", xlim = c(0,18), at = seq(0,18,3),
       print.tau2.ci = T, print.I2.ci = T,
       digits = 3, digits.pval.Q = 3, digits.I2 = 1,
       fs.hetstat = 12,
       addrows = 3)

dev.off()

# Cave: The column "Total" has to be changed manually afterwards to the number of mice via image editing.

# No moderator analysis was performed as we observed no significant heterogeneity of SAH grades.




#### Sham-operated mice

# We conducted no meta-analysis of the SAH grade in sham-operated mice as the overwhelming number of articles reported a SAH grade of zero (means no SAH per definition).






###### Figure: Reporting quality of experimental parameters

# Loading data
SAH_PRQ <- read.csv("SAH perforation parameter reporting quality.csv")


## Plotting and saving:
pdf(file = "SAH_parameter_reporting_quality.pdf", width = 13.5, height = 8)

par(mar=c(14.5,5,2,1))
SAH_parameter_reporting_barplot <- barplot(SAH_PRQ$Reporting_ratio * 100,
                                           main = "Experimental parameters reporting",
                                           cex.main = 1.6,
                                           col = ifelse(SAH_PRQ$Reporting_ratio >= 0.5, "grey70", "grey90"),
                                           ylab = "Percentage of reporting",
                                           ylim = c(0,100),
                                           cex.lab=1.4,
                                           names.arg = SAH_PRQ$Parameter, las = 2, cex.names = 1.2)
grid(NA, NULL, col = "black")

# Adding values on top of the bars:
SAH_PRQ$Reporting_ratio_rounded <- round(SAH_PRQ$Reporting_ratio,3)
text(x = SAH_parameter_reporting_barplot, y = SAH_PRQ$Reporting_ratio_rounded * 100, label = SAH_PRQ$Reporting_ratio_rounded * 100, pos = ifelse((SAH_PRQ$Reporting_ratio_rounded * 100) > 50,1,3), cex = 1, col = "black")

dev.off()





##### Figure: Mortality ~ Time after SAH


## Mortality at t = 1:

# Creating a CSV for manual reconciliation (we need one row per article to not impair the independence of data included in the random-effects model):
MMAP %>% filter(Time == 1) %>% select(StudyIdStr, Experiment, NumberOfAnimals, Average, Vehicle.control.) %>% write.csv("MMAP_1day.csv", row.names = F)

# Loading reconciled data:
MMAP_1day_reconciled <- read.csv("MMAP_1day_reconciled.csv")
MMAP_1day_reconciled <- MMAP_1day_reconciled %>% filter(reconciled == "x")

# Calculating proportional effect sizes
MMAP_1day_reconciled$deaths <- round(MMAP_1day_reconciled$Average * MMAP_1day_reconciled$NumberOfAnimals / 100, 0)
MMAP_1day_reconciled <- escalc(xi = deaths, ni = NumberOfAnimals, measure = "PLO", data = MMAP_1day_reconciled)

# Random-effects meta-analysis:
MMAP_1day_MA <- rma(yi, vi, method = "DL", level = 95, data = MMAP_1day_reconciled)
MMAP_1day_MA
predict.rma(MMAP_1day_MA, transf = transf.ilogit)


## Mortality at t = 2:

# Creating a CSV for manual reconciliation (we need one row per article to not impair the independence of data included in the random-effects model):
MMAP %>% filter(Time == 2) %>% select(StudyIdStr, Experiment, NumberOfAnimals, Average, Vehicle.control.) %>% write.csv("MMAP_2day.csv", row.names = F)

# Loading reconciled data:
MMAP_2day_reconciled <- read.csv("MMAP_2day_reconciled.csv")
MMAP_2day_reconciled <- MMAP_2day_reconciled %>% filter(reconciled == "x")

# Calculating proportional effect sizes
MMAP_2day_reconciled$deaths <- round(MMAP_2day_reconciled$Average * MMAP_2day_reconciled$NumberOfAnimals / 100, 0)
MMAP_2day_reconciled <- escalc(xi = deaths, ni = NumberOfAnimals, measure = "PLO", data = MMAP_2day_reconciled)

# Random-effects meta-analysis:
MMAP_2day_MA <- rma(yi, vi, method = "DL", level = 95, data = MMAP_2day_reconciled)
MMAP_2day_MA
predict.rma(MMAP_2day_MA, transf = transf.ilogit)


## Mortality at t = 3:

# Creating a CSV for manual reconciliation (we need one row per article to not impair the independence of data included in the random-effects model):
MMAP %>% filter(Time == 3) %>% select(StudyIdStr, Experiment, NumberOfAnimals, Average, Vehicle.control.) %>% write.csv("MMAP_3day.csv", row.names = F)

# Loading reconciled data:
MMAP_3day_reconciled <- read.csv("MMAP_3day_reconciled.csv")
MMAP_3day_reconciled <- MMAP_3day_reconciled %>% filter(reconciled == "x")

# Calculating proportional effect sizes
MMAP_3day_reconciled$deaths <- round(MMAP_3day_reconciled$Average * MMAP_3day_reconciled$NumberOfAnimals / 100, 0)
MMAP_3day_reconciled <- escalc(xi = deaths, ni = NumberOfAnimals, measure = "PLO", data = MMAP_3day_reconciled)

# Random-effects meta-analysis:
MMAP_3day_MA <- rma(yi, vi, method = "DL", level = 95, data = MMAP_3day_reconciled)
MMAP_3day_MA
predict.rma(MMAP_3day_MA, transf = transf.ilogit)


## Creating a dataframe with times and mortalities:
options(digits = 1) 
MMAP_Time_Mortality <- data.frame(estimate = c(19.96,24.10,25.64), llci = c(16.75,19.19,17.84), ulci = c(23.61,29.81,35.38), time = c(1,2,3))
MMAP_Time_Mortality$vertical_position <- c(0.5,0.3,0.1)
MMAP_Time_Mortality$labels <- c("1 day after SAH", "2 days after SAH", "3 days after SAH")
MMAP_Time_Mortality$articles <- c(nrow(MMAP_1day_reconciled), nrow(MMAP_2day_reconciled), nrow(MMAP_3day_reconciled))
MMAP_Time_Mortality$estimate <- round (MMAP_Time_Mortality$estimate, 1)
MMAP_Time_Mortality$description <- paste(MMAP_Time_Mortality$estimate, " [", MMAP_Time_Mortality$llci, ",", MMAP_Time_Mortality$ulci, "]", sep = "")


## Plotting and saving as pdf:
pdf(file = "Mouse mortality depending on the time after SAH.pdf", width = 10, height = 7.5)

plot.new()
par(mar=c(5,8,2,1))
plot(NULL, xlim=c(0,40), ylim=c(0,0.6), ylab="", xlab="Mortality (%)", yaxp = c(0.1,0.5,3), yaxt = "n", main = "Mouse mortality depending on the time after SAH")
segments(x0 = MMAP_Time_Mortality$llci, x1 = MMAP_Time_Mortality$ulci, y0 = MMAP_Time_Mortality$vertical_position)
segments(x0 = MMAP_Time_Mortality$estimate, y0 = MMAP_Time_Mortality$vertical_position - 0.015, y1 = MMAP_Time_Mortality$vertical_position + 0.015, lwd = 3)
axis(2, at = MMAP_Time_Mortality$vertical_position ,labels = MMAP_Time_Mortality$labels, las = 1)
text(5,0.57, "Articles")
text(5, MMAP_Time_Mortality$vertical_position, MMAP_Time_Mortality$articles)
text(MMAP_Time_Mortality$estimate, MMAP_Time_Mortality$vertical_position + 0.02, MMAP_Time_Mortality$description, pos = 3)
segments(x0 = 3, x1 = 7, y0 = c(0.03, 0.59), lty = 2)
segments(x0 = c(3,7), y0 = 0.03, y1 = 0.59, lty = 2)

dev.off()

# Restoring digits setting:
options(digits = 6)
